Drei/lisp-syntax-commands.lisp, Drei/views.lisp, Lisp-Dep/fix-ecl.lisp, Lisp-Dep/mp-bt.lisp, mcclim.asd, package.lisp, utils.lisp
for now without threads and has some problems with example apps (didn't test on the other implementations), but the main window is created etc. Requires building ECL with bundled CLX.
=> ecl initil support and bordeaux-threads multithreading

Examples/gadget-test.lisp, gadgets.lisp, pixmap.lisp
A. Fix simple-error:
Backtrace:
0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION CLIM:SHEET-MIRROR (3)> #<CLIM-INTERNALS::MIRRORED-PIXMAP {10111572F3}>) [fast-method]
1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION CLIM:SHEET-MIRROR (3)> (#<CLIM-INTERNALS::MIRRORED-PIXMAP {10111572F3}>))
2: ((:METHOD CLIM:MEDIUM-DRAW-POINT* (CLIM-CLX::CLX-MEDIUM T T)) #<CLIM-CLX::CLX-MEDIUM {1011157573}> 0 0) [fast-method]
------
B. Improve activate/deactivate widgets
=> sheet-mirror ((pixmap mirrored-pixmap))

Core/clim-core/defresource.lisp, Extensions/fonts/xrender-fonts.lisp
Considering that ATOMIC-INCF, ATOMIC-DECF are not suppurted anymore I add two simple macros for defresource. 
The default location of ttf in archlinux is #p"/usr/share/fonts/TTF/".
=> atomic-incf/decf & ttf paths

Backends/CLX/port.lisp, Extensions/fonts/xrender-fonts.lisp
xrender-fonts from the truetype extensions specializes on the port and
text style while the text-style-to-X-font is an ordinary function by
default.
This was hacked out by calling FMAKUNBOUND and defining the
method (which implicitly created a generic function). Hack is removed in
favour of making a function generic and providing a default method.
=> text-style-to-X-font: make function generic

Libraries/Drei/input-editor.lisp
vector-push-extend was called with the optional argument which could 0, what lead to the condition in the debugger preventing from intermixing some presentations and the S-expressions. This removes this optional argument.
=> input-editor: fix call to vector-push-extend

Extensions/fonts/fontconfig.lisp, Extensions/fonts/xrender-fonts.lisp
On Debian 8.2.0, the `(mcclim-truetype::build-font/family-map)` will returns
```
(((:SERIF :ROMAN) . #P"/usr/share/fonts/truetype/arphic/uming.ttc")
((:SERIF :BOLD) . #P"/usr/share/fonts/truetype/arphic/uming.ttc")
((:SERIF :ITALIC) . #P"/usr/share/fonts/truetype/arphic/uming.ttc")
((:SERIF (:BOLD :ITALIC)) . #P"/usr/share/fonts/truetype/arphic/uming.ttc")
((:SANS-SERIF :ROMAN) . #P"/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc")
((:SANS-SERIF :BOLD) . #P"/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc")
((:SANS-SERIF :ITALIC) . #P"/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc")
((:SANS-SERIF (:BOLD :ITALIC))
. #P"/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc")
((:FIX :ROMAN) . #P"/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc")
((:FIX :BOLD) . #P"/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc") …
```
=> Fix the mcclim-truetype on Debian 8.2.0

Extensions/fonts/fontconfig.lisp, Extensions/fonts/xrender-fonts.lisp
This code is provided by @dkochmanski .Thanks for his help. After this fix, McCLIM demos can be run on Debian after use `CONTINUE` restart from a warning:
```
NOTE:
* McCLIM was unable to configure itself automatically using
fontconfig. Therefore you must configure it manually.
```
=> fix fontconfig on Debian

Core/clim-basic/regions.lisp
Hi Daniel,
the solution that you proposed is fine.
I have seen that the bands are always ordered so we can quit if we y is smaller than y2.
The example "10) Clipping Region" of drawing tests uses this method.
Alessandro
=> fix region-contains-position-p

Libraries/Drei/drei.lisp, Libraries/Drei/packages.lisp, Libraries/Drei/syntax.lisp, Libraries/ESA/esa.lisp, Libraries/ESA/packages.lisp
Introduce esa-command-table generic function (instead of implicit one
command-table). This method is used in Drei, so we have to export it.
=> esa: don't leak generic function to clim package

Backends/CLXv3/frame-manager.lisp, Backends/CLXv3/port.lisp, Backends/Standard/events.lisp
the %realize-mirror for basic-sheet is surplus. They are not called as in all tests of clim:demodemo. Add a brief doc string for two event-port-mixin.
#128
=> some clean up in clxv3

Core/clim-core/dialog.lisp
This will fix #132.
If accept returns we must not rescan the text field.
=> dialog: do not finalize an accepted object

Core/clim-core/panes.lisp
fix for accepting-values with :own-window t for clxv3 and clxfb backends.
=> fix window-stream for single mirrored backends

Apps/Listener/dev-commands.lisp, Core/clim-basic/utils.lisp, Core/clim-core/commands.lisp, Libraries/ESA/packages.lisp, Libraries/ESA/utils.lisp, package.lisp
This is a first step towards removing local utility functions and macros and replacing them with implementations provided by the Alexandria library.
Functions and macros used: `CLAMP`, `PARSE-ORDINARY-LAMBDA`, `MAKE-KEYWORD` and `ONCE-ONLY`.
=> Increase Alexandria usage

Backends/CLX/port.lisp, Core/clim-basic/clim-basic.asd
Also added :trivial-features to clim-basic.asd.
I tested this in Windows with SBCL and CCL and XMING server 6.9.0.31 (looks fairly out-of-date).  
SBCL works fine.  
I found that CLX w/ CCL is giving an error related to the X server version being incompatible.  I'm going to attempt to find out why SBCL works, but CCL doesn't on my machine, but I think that's outside of this issue.
=> Use internet socket w/ localhost when connecting to CLX on Windows.

Core/clim-basic/graphics.lisp
* before, we would call (apply #'invoke-with-drawing-options
... (list ,@drawing-options). Now we just
do (invoke-with-drawing-options ... ,@drawing-options).
This avoids a compiler warning from SBCL about the third argument
not being a constant (and why cons up a new list and call apply
anyway?).
=> with-drawing-options: call invoke-with-drawing-options directly

Extensions/bitmap-formats/bitmaps.lisp
* and throw it as an error if the opticl:read-image-file call
fails. Yes, there are other reasons this could fail, but this is
less bad than not handling that error at all.
=> resurrect unsupported-bitmap-format

Examples/tabdemo.lisp
* the underlying implementation must have changed. Ape the current
implementation of find-pane-named and use string-equal for the
comparison.
=> fix sane-find-pane-named

Examples/demodemo.lisp, Examples/sliderdemo.lisp
* it was clobbering some of calc's symbols. probably ok since
sliderdemo appears to be just a cut-and-pasted version of calc,
but, still, let's be on the safe side.
=> put sliderdemo in its own package

Extensions/bezier/bezier.lisp, Extensions/bezier/mcclim-bezier.asd
* add methods that specialize on the render-medium-mixin and call the
mcclim-render backend code to do the bezier curve drawing.
=> use mcclim-render backend for drawing bezier curves

Examples/drawing-tests.lisp, Extensions/bezier/bezier.lisp, Extensions/bezier/package.lisp
moves all the bezier code into mcclim-bezier and import-from's the appropriate symbols from the other packages, instead of doing (in-package :...) to get access to symbols from null, render, and postscript backends.
Also, fix up the bezier-area drawing-test example and add a couple FIXMEs.
=> Bezier package improvements

Extensions/bezier/bezier.lisp
* we weren't taking into account the starting position of the design
and were overtranslating it
=> fix translation of output-record

Extensions/bezier/bezier.lisp
With these changes we can no take point-seq's and coord-seq's instead of just lists of points and coords. Furthermore, segments can, internally, be either a list or a vector (or other sequence, presumably).
=> More bezier stuff

Core/clim-core/gadgets.lisp
If visible-items is nil, then we take length of items list, otherwise
we take the assigned valuee.
Thanks to that programmer can assign NIL again. Defaults to NIL.
=> visible-items: don't assign meaning to unbound slot

Examples/font-selector.lisp, Extensions/layouts/tab-layout.lisp
Previously we have taken pane width as x2. Since we count from 0,
(width,17) was one more than last pixel on the pane what caused
alloc-space to make the pane bigger. i.e pane width is 5, then last
point is (4,y).
cosmetic: use accessor instead of raw slot value.
=> tab-layout: draw-line* takes x1 y1 x2 y2 parameters, fix alloc-space

Backends/Standard/sheets.lisp
A small fix that improves the performance of single-mirrored backends.
=> dispatch-repaint directly on the mirrored-sheets

Core/clim-core/frames.lisp, Core/clim-core/gadgets.lisp, Core/clim-core/menu-choose.lisp, Core/clim-core/menu.lisp
It solves #171.
unmanaged-top-level-sheet-panes are created disabled as top-level-sheet-panes.
=> unmanaged-top-level-sheet-pane requires to be enabled

Examples/clim-fig.lisp, Examples/drawing-tests.lisp, Extensions/bezier/bezier.lisp
Now we properly set a pixmap-based mask based on the positive and negative areas of a bezier difference when drawing with the CLX backend.
=> Bezier clx draw rewrite

Core/clim-core/panes.lisp
#225 
Window-clear must not change the user space requirements.
=> fix change-space-requirements

Examples/clim-fig.lisp
* this allows for thicker curves and rouned caps on bezier
lines. currently a new op for bezier areas, but arguably we should
draw a thicker perimeter for bezier areas. use the argument anyway
for good measure.
=> use :line-style arg for bezier drawing

Core/clim-basic/stream-output.lisp, Core/clim-core/panes.lisp, Libraries/Drei/drei-redisplay.lisp, Libraries/Drei/packages.lisp
Make the space req protocol closer to the spec.
- the user space requirements are never changed 
-  'redisplay-frame-pane' calls 'change-space-requirements' only if a user req is equal to :compute. This improves the overall performance of clim.
- stream-output does not depend on pane protocol.
- 'window-clear' does not change user space width and height to zero.This improves the overall performance of clim.
=> improve space requirement protocol

Backends/CLX/basic.lisp
CLX isn't very thread-safe, but most of the errors are not
critical (i.e shifted response) and doesn't influence overall
effect. When we handle these errors, user is dropped into the
debugger, and closing it breaks X connection.
Workaround is to ignore errors for asynchronous connections. Also we
log each error on with log4cl.
=> don't die on asynchronous errors

Extensions/image/clx-image.lisp, package.lisp
The previous commit broke a few applications: spectacle and sudoku.
=> fix symbols in mcclim-image package

Backends/PDF/paper.lisp
modifies the pdf-transformation to allow for a one pixel margin. without this, text would get cutoff at the top of the page.
=> add a 1 unit margin to PDF output

Backends/CLX/medium.lisp, Core/clim-basic/recording.lisp, Extensions/bezier/bezier.lisp
These changes make it so that the output-recording coord-seq can be a seq, not just a vector, and fix a bunch of bugs encountered along the way. Previously, the functions under the covers only worked with vectors, but the drawing code for draw-lines, draw-points, draw-polygon, etc... only worked if we passed in a list which was copied to a vector. Now we can pass in either a list or a vector and the code under the covers should work with both lists and vectors. We still copy the sequence, as the copy gets transformed during the playback of the output record, but things are much less broken.
draw-rectangles, OTOH, was completely broken in multiple ways. It, too, is fixed, using the coord-seq-mixin infrastructure.
In general, all this output-recording/drawing code is a big hacky mess, but …
=> Output recording coord seq mixin

Backends/CLX/keysyms-common.lisp, Backends/CLX/keysyms.lisp
This is the fix to the issue #175 
The problem with caps lock was that 
(a) it was not recognized when caps-lock key was pressed (instead, the shift-lock was recognized)
(b) it did not handle the casing properly
I have tested this fix on my machine. I have changed the right shift with "Shift_Lock" modifier (instructions can be found here: http://xahlee.info/linux/linux_shift_lock_key.html )
When pressing the caps-lock, it is recognized and applied to the keysym.
When pressing shift, it is recognized and applied to the keysym.
When pressing both, they are recognized and applied correctly.
I have also removed shift-lock from the files I have edited. The reason for that is the way the shift-lock works; rather than triggering shift-lock key, it actually works as if the user was holding the …
=> Fix caps lock affecting non-alphabetic keys

Core/clim/text-editor-gadget.lisp, Libraries/Drei/drei-clim.lisp, Libraries/Drei/syntax.lisp
The way this was implemented previously, namely passing the value of the ``value-changed-callback`` _initarg_ to the substrate object, bypassed the ``value-changed-callback`` _method_ of the ``text-editor-pane`` instance, violating the description of ``value-changed-callback`` in [30.3 (Basic Gadget Classes)](http://bauhh.dyndns.org:8000/clim-spec/30-3.html#_6734).
With this change a value-changed callback is installed in the substrate object that invokes the ``value-changed-callback`` method for the ``text-editor-pane``.
Another (potential) benefit of this change is that the ``id`` and ``client`` initargs can be handled by the ``text-editor-pane`` instance normally instead of being passed to the substrate object. This seems more
accurate and more robust (e.g. in case the id and/or client …
=> Text editor pane value changed callback fix (with bonus spelling fixes)

Apps/Listener/dev-commands.lisp, Core/clim-basic/utils.lisp, Core/clim-core/commands.lisp, Libraries/ESA/esa-mcclim.asd, Libraries/ESA/packages.lisp, Libraries/ESA/utils.lisp, package.lisp
* PARSE-ORDINARY-LAMBDA-LIST
* MAKE-KEYWORD
McCLIM's own implementation used to be a no-op if the argument was a
keyword.  However, CL:INTERN handles keywords gracefully.
* ONCE-ONLY
* WITH-GENSYMS
* CLAMP
=> Use Alexandria-provided macros and functions

Apps/Listener/file-types.lisp
* if we call (skip-whitespace "" 0) we return nil. Rather than
changing that behavior, check to see if the return value is nil
before attempting to sue it as an index for position-if. If it's
nil, don't attempt to parse the string.
* fix indentation in skip-whitespace
=> check return value of skip-whitespace before using it

Core/clim-core/gadgets.lisp, Core/clim-core/menu.lisp, Examples/colorslider.lisp, Examples/gadget-test-kr.lisp, Examples/traffic-lights.lisp, package.lisp
standard-gadget was some leftover from past time (GB comments indicate, that he was wondering about its purpose too). It's not standard nor exported. Reduce class hierarchy complexity by 2.
=> minor cleanup: remove undocumented internal class

Backends/PDF/class.lisp, Backends/PDF/paper.lisp, Backends/PDF/sheet.lisp
Various PDF enhancements. The big one (for me anyway) is that I can now make a PDF to a certain size, including just the size of the output.
* add trim-page-to-output-size keyword argument to
clim-pdf:with-output-to-pdf-stream
* device-type can now be a list of the form (width height) to specify
the page size, instead of being locked into the fix named paper
sizes
* landscape printing is better, but text prints rotated 90
degrees (that is to say that it isn't rotated, as it should be).
* add orientation accessor
* make sheet-native-transformation be an acessor, not just a reader
=> Pdf backend improvements

Backends/CLX/medium.lisp, Examples/clim-examples.asd, Examples/method-browser.lisp, Examples/tabdemo.lisp, Extensions/layouts/tab-layout.lisp
Mainly this:
Other than that:
* improve behavior of ``text-size`` for not fully specified text styles
* fix mop use method-browser example
* cleanup in tabdemo
* tab layout does not offer to switch to already selected tab
=> Prettier page header highlight in tab layout

Core/clim-basic/recording.lisp, Core/clim-core/dialog.lisp
We provide intelligible message for malformed accepting-values call (see #308).
Alse multiple-values if present are returned from body.
=> Fix accepting values

Extensions/render/color.lisp
* before we would occasionally call octet-mult with a negative
number. This worked, but the function declamation says it should
only take octets and recent SBCL compilers are smart enough to see
that we were violating this assumption. So, rewrite %lerp to always
call octet-mult with bona fide octets.
=> rewrite render backend %lerp to use octets

Core/clim-core/dialog.lisp
Instead just overwrite them till the 'accepting-values' is active. it will be automatically restored when 'accepting-values' finishes. See #164.
=> Fix-164: Do not append keystrokes to *accelerator-gestures*

Core/clim-core/gadgets.lisp, Core/clim/text-editor-gadget.lisp, Libraries/Drei/drei-redisplay.lisp
+ I have changed button spacing because It had very low padding. (`g` and `y` will touch the button boundry. see first column of buttons in `demodemo`)
+ Block cursor is replaced with a line cursor of `3` pixel width. Tested with listener, climacs and different editor widgets.
+ Fixed #317 .
=> Improve text field gadget

Examples/tabdemo.lisp
The "Quit" menu option is disabled in the tabdemo.lisp example program; this commit changes the reference to nonexistent com-quit-tabdemo in the 'tabdemo-pages-menu command table to com-quit.
=> Fix disabled quit option in pages menu of tabdemo.

Core/clim-core/dialog.lisp
from the pane It is called in. Fixes #444 .
=> accepting-values : Inherit query box background and foreground ink

Examples/drawing-tests.lisp
* we need to (copy-to-pixmap stream ...) to draw on the
stream/medium's pixmap. copy-to-pixmap takes a medium as its first
argument, not a pixmap.
=> fix Pixmap 3 drawing test by fixing args to copy-to-pixmap

Libraries/Drei/core-commands.lisp
This little change resolves the following error when insert key is pressed to turn on overwrite mode in text-field-pane:
```
When attempting to read the slot's value (slot-value), the slot
DREI:OVERWRITE-MODE is missing from the object
#<DREI:TEXTUAL-DREI-SYNTAX-VIEW name: *scratch* 1 {1006EBF113}>.
[Condition of type SIMPLE-ERROR]
Restarts:
0: [ABORT] Return to application command loop
1: [RETRY] Retry SLY mREPL evaluation request.
2: [*ABORT] Return to SLY's top level.
3: [ABORT] abort thread (#<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {10043B58E3}>)
```
=> There is no overwrite-mode slot in textual-drei-syntax-view class

Extensions/bitmap-formats/bitmaps.lisp, Extensions/image/bitmap.lisp, Extensions/image/package.lisp
opticl isn't great at guessing file types. It appears to use the file extension in order to guess, which isn't always correct.
In cases where the user is providing a `:format` argument, we shouldn't make opticl try to guess, since the user has told us what format the file is. The current code ignores the ':format' argument for common formats that opticl is used to decode. This fixes that.
Previously, these didn't work - opticl couldn't guess because of the lack of an extension - but now they do:
```
CL-USER> (clim:make-pattern-from-bitmap-file "/home/kyle/Documents/12pbm" :format :pbm)
#<CLIM-EXTENSIONS:RGB-PATTERN {10309BD053}>                                                                                                                                                          
CL-USER> …
```
=> Improve image -> pattern code by calling specific opticl functions.

Core/clim-basic/repaint.lisp, Core/clim-basic/stream-input.lisp, Core/clim-basic/stream-output.lisp, Core/clim-basic/text-selection.lisp, Core/clim-core/panes.lisp
- previously mixin was specialized on a pane, but methods were specialized on
extended streams, what lead to erros when trying to select on (for instance) a
gadget - now we mix it in onlhy for standard-input-stream and
standard-output-stream what resolves this (unreported) issue;
- in repaint protocol we have used pane-background instead of medium-background
what lead to regression in drawing text-selection background - we fix
that (closes #470);
- previously selection background was blue and text was white – I've changed to
to while-yellow/red what imho looks much better - very opinionated tweak.
=> ux: text-selection: be more specific with the mixin

Extensions/layouts/tab-layout.lisp, Extensions/render/backend/fonts.lisp, Extensions/render/backend/port.lisp
Bugs found running demodemo: add new page to tab-layout caused error; truetype font cache failed and caused error; and, text width calculation didn't match text drawing code.
More details in commit log messages.
=> Fittestbits/demo fixes2 - three small bug fixes

Apps/Debugger/clim-debugger.lisp, Apps/Inspector/inspector.lisp, Examples/method-browser.lisp, Extensions/render/image-fast-ops.lisp, Extensions/render/image-ops.lisp
The inspector was printing some inspected values to *standard-output* instead of the pane.
The method-browser demo has been made more robust.
Additional type declarations have been added to the opticl image function to improve performance.
=> A few minor fixes

Backends/CLX/fonts.lisp, Backends/CLX/medium.lisp, Core/clim-basic/medium.lisp, Examples/text-size-test.lisp, Extensions/fonts/xrender-fonts.lisp, Extensions/render/backend/port.lisp
According to the spec, the keyword :FIX should be used to indicate a
fixed-width font. In various places in the code, the additional
keyword :FIXED was also allowed, and spacial cases were implemented to
transform that to :FIX.
However, this was not consistent, and specifically the implementation
of TEXT-STYLE-FIXED-WIDTH-P returned true only for the case where the
font was set to :FIXED.
This fix removes any reference to :FIXED, in order to make the API
consistent. One of the examples in clim-examples was also changed to
use :FIX instead of :FIXED.
=> Remove the inconsistency between :FIX and :FIXED

Core/clim-basic/repaint.lisp, Libraries/Drei/input-editor.lisp, Libraries/ESA/esa.lisp
* Revert the part of 9412163 , text-selection seems to work correctly without it. Fixes #484 
* Revert c9176a9 , it breaks ESA and copy-paste. Fixes #490 ,Re-opens #378.
=> fixes for #490 and #484

Extensions/fonts/freetype.lisp
It turnes out that locking freetype per face was not enough. Any
parallel access to Freetype creates a potential race condition.
=> Implement a global lock for freetype access

Backends/CLX/mcclim-clx.asd, Backends/CLX/package.lisp, Backends/CLX/port.lisp, Backends/CLX/text-selection.lisp, Core/clim-basic/clim-basic.asd, Extensions/fontconfig/src/fontconfig.lisp, Extensions/fontconfig/src/functions.lisp, Extensions/fontconfig/src/package.lisp, Extensions/fonts/common.lisp, Extensions/fonts/freetype.lisp, Extensions/fonts/mcclim-fonts.asd, Libraries/Drei/drei-mcclim.asd, Libraries/Drei/drei-redisplay.lisp
Implement support for font replacement.
Apart from changes to the fontconfig library that were needed to provide the ability find fonts that contains certain characters, the main user-visible change is a new function: `FIND-REPLACEMENT-TEXT-STYLES` which splits a string into sections with different text styles that should be used in order to make sure all characters are displayed.
Drei has been modified to take advantage of this function so that it is able to handle text of any language (with the exception of right-to-left text, this requires further changes).
=> Replace font

Core/clim-basic/regions.lisp
Not all subclasses of TRANSFORMATION offer the MXX, MXY, etc. slots.
Use the GET-TRANSFORMATION function to obtain these values instead in
%ELLIPSE-SIMPLIFIED-REPRESENTATION/RADIUS.
=> #500: Don't directly access TRANSFORMATION slots

Extensions/fonts/freetype.lisp
Sometimes there may be requests to draw text just outside the text
area. If coordinate swizzling is active, this area will be just above
position #xFFFF. Such strings should not be visible, but if an attempt
is made to actually copy these characters to the window, xlib will
throw an exception because the coordinate is out of range.
This fix ensures that no characters are drawn outside the valid range.
=> Freetype: Don't crash when coordinate swizzling is active

Core/clim-basic/ports.lisp, Core/clim-basic/stream-input.lisp, Core/clim-core/panes.lisp
- Omission/bug in McCLIM. Function CLIM:STREAM-SET-INPUT-FOCUS is part of The
Extended Input Stream Protocol hence method must be implemented for
CLIM:STANDARD-EXTENDED-INPUT-STREAM. Since CLIM:CLIM-STREAM-PANE inherits from
the former then we have no need to define this method for the latter (remove
method specialization).
- Don't check if focus belongs to the current *application-frame* in
(SETF CLIM:PORT-KEYBOARD-INPUT-FOCUS). This loosing of the requirement should
allow sharing some extended-input-streams between frames. Without this hcnage it
would be impossible to (SETF CLIM:PORT-KEYBOARD-INPUT-FOCUS) on
CLIM:STANDARD-EXTENDED-INPUT-STREAM rendering class unfittable to use as it is.
=> standard-extended-input-stream: usability fixes

Core/clim-core/incremental-redisplay.lisp
Incremental-redisplay works by calling compute-difference-set which
collects a list of drawing operations which are to be performed. It
does this by pushing the output records to a list. This results in the
order of the output records being reversed, which causes them to be
drawn in the wrong order. This behaviour can be seen when adding
two graphics operations to an updating-output form which draws on top
of each other. After redisplay, the output records will have been
drawn in reverse order.
This fix simply calls REVERSE on the list before returning it.
=> Fix repaint order in incremental-redisplay

Examples/image-transform-demo.lisp, Extensions/fonts/freetype.lisp
This pull request contains three fixes:
**Fix 1**
When applying the CLIM transformation matrix when loading characters using Freetype, the rotation direction is wrong. The previous solution was to transpose the matrix. This works for rotation, but ends up applying skew transformations along the wrong axis.
This fix solves the problem in the correct way by negating the xy and yx values.
**Fix 2**
The skew transformation matrix in the image-transform demo was computed as the product of the x-skew and y-skew vectors. This fix uses a single x and y skew matrix.
**Fix 3**
Some text was added to the image-transform demo in order to be able to verify that text transform works.
=> Transform fix

Backends/CLX/medium.lisp
This fix makes sure that the picture objects that are cached in the drawable are actually freed after being removed.
=> Explicitly free old picture objects

Core/clim-basic/sheets.lisp
Previously, the CHILDREN slot has an initarg called :CHILDREN. This
initarg was not usable since none of the logic implemented by
SHEET-ADOPT-CHILD was performed.
This fix changes this so that SHEET-ADOPT-CHILD is called once for
each child. It also renames the keyword argument to :CONTENTS in order
to be consistent with other panes.
=> Fix the :CONTENTS initialiser for SHEET-MULTIPLE-CHILD-MIXIN

Core/clim-basic/sheets.lisp, Core/clim-core/panes.lisp
The previous fix 204d80c6815cf7448d43f9d5d8fb05dac37bf8ca added a
:CONTENTS initarg to SHEET-MULTIPLE-CHILD-MIXIN. This was problematic
as it conflicted with other implementations of the same argument.
This fix moves this code to the BBOARD-PANE specifically. If it's
needed for other classes, they should be implemented for each one
individually.
=> Don't implement :CONTENTS initarg on SHEET-MULTIPLE-CHILD-MIXIN

Backends/CLX/input.lisp
X generates a button-press and a button-release event on each scroll-wheel change. The code assumes that only one scroll-wheel event should get generated on scroll wheel movement and only generates the event on button-press.
=> filtered button-release for pointer-wheel events

Backends/CLX/medium.lisp, Core/clim-core/panes.lisp
The optimised scroll implementation implemented scrolling by copying
the content of the window instead of repaining it. This worked
sometimes, but was problematic when a window was partially visible.
As it turns out, the proper way to do this is to always draw the
window content to a backing pixmap so that the previous content is
always available. If this is done, not much of the old code will be
useful anyway, so to clean things up this commit removes all of the
unused code.
=> Remove old code that was part of the optimised scroll

Core/clim-basic/recording.lisp, Core/clim-basic/stream-output.lisp, Core/clim-basic/transforms.lisp, Core/clim-core/panes.lisp
These changes were extracted from my current medium work and are unrelated to it (still needed and being improvement).
- compose-x-with-y transformation functions had arguments reversed
- small cleanup for scroll methods and initargs (no distracting unused code)
- specialization for mediums to be able draw on non-stream sheet inside with-room-for-graphics
I hope to make a follow-up pull request wrt invoke-with-room-for-graphics, but this will be bigger task and I don't want to get distracted from what I'm doing now.
=> Small changes

Examples/postscript-test.lisp
* (with-scaling 50) was causing text to be way too big. use
with-scaling 2 and adjust loop step size to fix align-x/align-y
text tests
=> fix clim-demo::postscript-test page 6

Apps/Scigraph/dwim/draw.lisp, Apps/Scigraph/scigraph/annotated-graph.lisp
* this allows for properly rotated text
* adjust text angle and position for proper vertical
positioning/orientation.
=> scigraph: use draw-string instead of draw-vertical-text

Core/clim-core/commands.lisp
Differences:
- if presentation type is an atom, we autoquote it
(if we really want to put evaluated variable here, do (identity ptype))
- we requiere macroexpand-constants for keyword specifiers
Improvements:
- we enforce a set of allowed keywords in argument description
- extra allowed keywords are PROMPT-MODE and INSERT-DEFAULT to prevent breaking
ESA. Do they work? ESA should be fixed in this regard.
Fixes #540.
=> define-command: be more conforming with evaluating argument descriptions

Libraries/Drei/drei-clim.lisp
* not just (drei-area *). This ensures that our region-union,
region-intersection, and region-difference methods, which extract
the bounding-rectangle of the drei area before re-calling the
region-* method, get called instead of methods that specialize
on (region region).
=> specialize region-* methods on (drei-area region) and vice versa

Backends/CLX/medium.lisp, Core/clim-basic/clim-basic.asd, Core/clim-basic/pattern.lisp
I had to fix these things in order to load McCLIM without warnings or errors.
One is due to unusual `*read-default-float-format*`, but that used to not be a problem.
=> Fix breakage from "medium-transformation-fixes" merge

Apps/Scigraph/dwim/present.lisp, Core/clim-core/incremental-redisplay.lisp, Examples/puzzle.lisp
I got rid of climi::convert-from-relative-to-absolute-coordinates
=> Examples/puzzle.lisp: no longer uses non exported symbols

Examples/demodemo.lisp
set the background to `climi::*3d-normal-color*` is not necessary:  it's already the default background of `basic-pane`.
=> Examples/demodemo.lisp: no longer uses non-exported symbols

Examples/patterns.lisp, Extensions/render/image.lisp, Extensions/render/utilities.lisp
* The `inline` declamations in `Extensions/render/*.lisp` work better when textually preceding the functions they refer to.
* An `ftype` declamation for `%octet-mult` referred to `octet-mult` instead.
* The new `Examples/patterns.lisp` demo used float literals without exponent markers in conjunction with specialized arrays. This leads to errors with non-standard `*read-default-float-format*` values.
* The same demo referred to the `*draw*` variable before its definition.
=> Fixes for render and pattern changes

Backends/RasterImage/rgb-port.lisp
* without this the various multiple-inheritance of rgb-image-pixmap
results in an initform of :nil whereas the slot is designed to be a
region, not (or null region).
* The error only shows up (I think) when running with safety 3, but
seems like a legitimate error.
=> provide :initform for rgb-image-pixmap

Core/clim-basic/utils.lisp
There are other errors loading mcclim in clasp, but these are errors in clasp, so I don't want to workaround in mcclim
=> Define getenv for clasp

Core/clim-basic/stream-output.lisp
We follow a typographical rule of 2.5 alphabets for paragraph width in a rare
event when stream region is +everywhere+ (most notably for PostScript :eps
streams).
=> stream-text-margin: don't use +fill+ which is a panes module var.

Extensions/bezier/bezier.lisp
Wow. one liner fixes the un-optimized bezier drawing in both CLX and render backends.
=> call medium-draw-bezier-design* on (sheet-medium sheet)

Apps/Scigraph/scigraph/frame.lisp
Simple bug fix for Scigraph. 
Invalid initialization argument:
:INITIAL-CURSOR-VISIBILITY
:initial-cursor-visibility initarg is not accepted in application-pane  initialization and it is not in the specification.
Before commit 
9434255f * bad protocol-classes: remove runtime overhead, restore initarg checking
this didn't produce an error, now it does.
=> Scigraph: bug fix

Libraries/ESA/esa.lisp
* remove :borders arg and :scroll-bars from ESA application-pane
subclass :default-initargs. The spec and our current code don't
explicitly allow for this. Whether they should allow this or not is
another issue and there is a separate Issue open to address this
<https://github.com/McCLIM/McCLIM/issues/628>. In the meantime, fix
the default :initargs so ESA panes work with current McCLIM.
=> ESA pane subclass :default-initargs fixes

Core/clim-core/gadgets.lisp, Core/clim-core/panes.lisp
This re-implementation uses a different approach: instead of tweaking the space requirements of the left and right client, the box client strategies (fixed size, proportional size, fill) are adjusted in a way that reserves the general strategy (e.g. a client using fill above a client using proportional) but changes the parameters.
Furthermore, instead of tracking an offset from the start point of the drag, the pointer position in the coordinate system of the left child is tracked. This is necessary for the implementation strategy described above.
=> Box adjuster improvements

Core/clim-basic/utils.lisp
Previously PARSE-SPACE will raise an error if the specification was a
non-integer number. This was the case even if the number is a floating
point number with a zero fractional part. The error is raised by a
call to ETYPECASE which checks for an integer.
This can happen if one sets a font size to fractional size and
attempts to display a FORMATTING-TABLE. The implementation of
FORMATTING-TABLE reads the STREAM-VERTICAL-SPACING, which is now a
floating-point number and passes it to PARSE-SPACE.
This fix changes the check from INTEGER to REAL so that any kind of
number is supported.
=> Make PARSE-SPACE handle all real numbers

Core/clim-basic/pattern.lisp
Previously, ROUND was used to ensure that the arguments to DESIGN-INK
were integers. This caused a problem in some situations when the
coordinates have a fractional part of 0.5. In such cases, ROUND will
either round up or down depending on whether the integer part is odd
or even.
Fixes https://github.com/McCLIM/McCLIM/issues/641
=> In DESIGN-INK, use consistent rounding for coordinates

Core/clim-basic/stream-input.lisp
The change 104b3157d871cfb445a9521dc2225caad503dac9 introduced a
problem where modifier keys could not be used together with return.
This fix restores the old behaviour.
Fixes https://github.com/McCLIM/McCLIM/issues/668
=> Resolve regression in CONVERT-TO-GESTURE

Core/clim-basic/stream-output.lisp, Core/clim-core/bordered-output.lisp, Core/clim-core/dialog.lisp, Core/clim-core/incremental-redisplay.lisp, Core/clim-core/input-editing.lisp, Core/clim-core/menu-choose.lisp, Core/clim-core/pointer-tracking.lisp, Core/clim-core/presentation-defs.lisp, Core/clim-core/table-formatting.lisp
While I get the sentiment that &key and &optional are something what will stay
in codebase (because that's how CLIM is specified) so we don't need
style-warnings about that, these local declarations muffle *all* style warnings
what is plain wrong.
These are legitimate style warnings anyway and I see nothing wrong with the fact
it is signalled. Commit doesn't introduce any functional changes, just removes
(locally (declare (sb-ext:muffle-conditions style-warning)) …) declarations.
=> cleanup: don't muffle style-warnings

Core/clim-basic/stream-output.lisp, Core/clim-basic/utils.lisp, Core/clim-core/panes.lisp, Examples/demodemo.lisp, Examples/seos-baseline.lisp
- stream text split functions (for wrapping) should be faster now thanks to bisection (instead of naive letter-by-letter algorithm)
- end-of-line-action accepts now `:wrap*` for wrapping by word
- end-of-page is now recognized even when text-style changes size on a line
- new internal protocol introduced.
stream-effective-left-margin
stream-effective-right-margin
stream-effective-top-margin
stream-effective-bottom-margin`
Right now all except the right margin resort to window size (0,0,text-margin,window-height), they will have more useful implementation in upcoming PR with margin-mixin. Related parts of code has been adjusted to honor results of these functions.
=> seos: split functions, margins and end-of-*-action changes

Core/clim-basic/mirrors.lisp, Core/clim-core/panes.lisp
As described in #499, when a window partially leaves the screen to the
left, its contents slides to the left and even "accelerates".
This change fixes the transformation computation performed in response
to window configuration events which caused the problem.
=> Fix content sliding to the left when window leaves screen

Apps/Scigraph/dwim/package.lisp, Apps/Scigraph/dwim/present.lisp
Following the suggetion of @slyrus I split PR #706 in three part. This is the third part about Scigraph accept function.
The ACCEPT version in DWIM package produced a SHEET-IS-NOT-A-CHILD
error when a dialog with gadget was closed.
This is due to how QUERY-IDENTIFIER parameter was passed to the
CLIM:ACCEPT function.
Because the Scigraph version in McCLIM is a CLIM2 only application the
DWIM:ACCEPT compatibility layer is no more necessary.
For this reason this commit remove the function ACCEPT from DWIM
package and now Scigraph use directly the CLIM:ACCEPT function.
=> Scigraph: remove accept from dwim package

Extensions/fonts/fontconfig.lisp
In Gentoo/Funtoo linux system, the font path for dejavu is `/usr/share/fonts/dejavu/`.
It will raise a warning if such path doesn't exist.
=> add dejavu font path in gentoo/funtoo system.

Core/clim-core/presentation-defs.lisp
Following the suggetion of @slyrus I split PR #706 in three part. This is the first part about clim 2.2 presentation options. These options are required by Schigraph as reported in issue #704. 
This PR only introduce the options but not implements their functionality. 
@slyrus also complained about `highlight-completion-choice` function that it is copied from CLIM-TOS. The function is still there  because @dkochmanski was ok with this, but if you want to remove it, it is not a problem. Until McCLIM don't use `highlighter` options in `accept-present-default` methods we can also use `nil` as default value for `highlighter`.
Finally: if McCLIM don't want implement clim2.2 features it is also ok but it will be necessary to remove the options in Scigraph code (maybe with a compatibility …
=> clim2.2 presentations options.

Core/clim-core/panes.lisp, Extensions/layouts/tab-layout.lisp
- ensure cons arity with destructuring-bind
- use etypecase on x value (real or cons) to avoid returning nil
- maximize text metric value on children when called on composite pane
- provide disjoint method for basic pane and extended-output-stream
=> panes: improve spacing-value-to-device-units

Core/clim-core/panes.lisp
The unit names are specified in http://bauhh.dyndns.org:8000/clim-spec/17-2.html#_922.
=> Rename the spacing unit :pixels to :pixel (discussed in issue #742).

Core/clim-core/frames.lisp
Extension is present but the protocol was never called. We may need it
in the future for some activate/deactivate actions (i.e we could
activate buttons by naviagting with tab).
=> note-input-focus-changed: resurrect the extension

Backends/CLX/port.lisp
The function supposes an occurence of at least one #\: in the DISPLAY
environment variable. This isn't guaranteed (for example, with XQuartz, DISPLAY
is set to computer-name.network-name), and in fact the use-localhost
restart of helpfully-automagic-clx-server-path passes an empty string onwards.
=> Fix Issue #783, automagic-clx-server-path

Core/clim-basic/events.lisp, Core/clim-basic/mirrors.lisp, Core/clim-core/panes.lisp
This PR solve #769 about the wrong sheet-transformation of a top-level-sheet-pane when it start outside the screen. 
For this it  revert the changes of commit a894385 in PR #691 and find another solution to fix 
the bug of issue #499 solved by that PR.
There is also some changes in window-configuration-event.
=> top-level-sheet-pane sheet-transformation

Backends/CLX/basic.lisp, Core/clim-basic/decls.lisp, Core/clim-basic/stream-input.lisp, Core/clim-core/pointer-tracking.lisp
This PR change the semantic of `pointer-position` that now return the position of the pointer in the graft coordinate. This is a possible interpretation of the clim specifications (section 22.4) different from what is written in Franz Manual (section 15.1).
The PR implements also the functions `(setf pointer-position)` and `(setf stream-pointer-position)` . 
This solve issue #768.
This PR have PR #774 as pre-requisite otherwise the position of `stream-pointer-position` when frame window start outside the screen it is not correct because the sheet-transformations are not correct.
=> Set pointer position

Examples/clim-fig.lisp
Re: https://github.com/McCLIM/McCLIM/pull/777#issuecomment-504334745
=> Fix 98fde3d: Add missing presentations for object creation and undo.

Libraries/Drei/core-commands.lisp
com-rotate-yank would only replace input when the previous command was a yank
rotation as well. Make it recognize com-yank as valid predecessor.
=> Fix rotate-yank (#779).

Backends/CLX/medium.lisp
Previously, requests to draw regions with larger edge size than 2048 were simply
skipped, but still marked as updated, with the effect that uninitialized
contents of the graphics memory were visible instead.
Fix it by halving the size of pixmaps until they are small enough for
xlib:put-image to handle.
=> Fix #744: Don't skip xlib:put-image for images larger than 2^11.

Examples/clim-fig.lisp, Extensions/bezier/bezier.lisp
Mostly contains changes to the clim-fig example:
- allow undo/redo of figure move actions
- activate and deactivate the undo/redo/clear buttons according to program state
- don't grow these buttons when resizing the window (thanks, scymtym)
And one related fix for bezier.lisp (1536c17)
=> Clim fig improvements (and related bug fix)

Backends/CLX/clipboard.lisp, Backends/CLX/graft.lisp, Backends/CLX/package.lisp, Core/clim-basic/input.lisp, Documentation/Manual/Texinfo/developer-manual.txi
This change unifies wait-function interpretation across different APIs and removes recursive locks from the concurrent-event-queue. Some minor fixes follow. This change is part of work for #712 without any stream-related changes (which are work in progress).
=> refactor 712 partial

Core/clim-core/panes.lisp
Caveat: there is some history to this type of change. For example, a468fc6
removed some "magic numbers", then 9dedf6b reintroduced them again a few days
later. It is advisable to look through the commit history before working
on this.
The basic problem is that panes without contents might result in computed space
requirements of 0x0 pixels, which aren't sensible (and the X protocol can't
handle). For these situations, some code paths had default values for width and
height, others did not. This commit normalizes those defaults to 100x100 pixels.
=> Specify and regularize default dimensions for panes. See #699

Core/clim-core/clim-core.asd, Core/clim-core/dialog-views.lisp, Core/clim-core/dialog.lisp, Libraries/Drei/lisp-syntax.lisp
Fixes these compilation warnings:
```
; file: [...]/McCLIM/Core/clim-core/dialog-views.lisp
[...]
; caught WARNING:
;   undefined variable: CLIM-INTERNALS::*ACCEPTING-VALUES-STREAM*
```
```
; file: [...]/McCLIM/Libraries/Drei/lisp-syntax.lisp
[...]
; caught WARNING:
;   undefined variable: DREI-LISP-SYNTAX::|initial-state |
```
=> Add declarations for variables that have not been defined yet.

Extensions/fonts/xrender-fonts.lisp
Previously we did resort to xlib fonts but that was bogus and caused
problems with method without specialization. To avoid further
confusion let's not fallback to fonts which does not work. Closes #705.
=> xrender-fonts: error when font can't be found

Extensions/Franz/franz.lisp, Extensions/Franz/mcclim-franz.asd, mcclim.asd, package.lisp
With commit 9f36c9e4 the functions pointer-input-rectangle,
pointer-input-rectangle* and pointer-place-rubber-band-line* were
removed. These are functions documented in the Franz Manual but not in
CLIM Specifications.
Here I re-add them but now the functions are exported in clime package.
This Fix #817 issue.
=> pointer-tracking: re-adding some franz-specific functions

Backends/CLX/mcclim-clx.asd, Backends/CLX/medium-xrender.lisp, Backends/CLX/path.lisp
- Add log4cl to the asd file
- change the triangle generation to use a vector of coordinates instead of all the lists.
(I can't tell much difference in terms of performance on my machine -- because XQuartz renders at snails pace anyway -- but I hope you see some on linux.)
=> wip: xrender 

Extensions/fonts/fontconfig.lisp
Guix doesn't follow FHS. 
The fontconfig package in Guix looks for fonts in `$HOME/.guix-profile` by default and dejavu is located in `~/.guix-profile/share/fonts/truetype/`.
=> add dejavu font path for guix system

Core/clim-basic/events.lisp, Core/clim-core/frames.lisp, Core/clim-core/menu.lisp, Core/clim-core/panes.lisp
* Destroy submenu structure depending on port's pointer sheet 
* Use correct frame when (de)activating menu items 
* The functions `menu-draw-[un]highlighted` are not used anywhere. The `(handle-repaint menu-button-pane t)` method seems to be an improved version of these functions.
* Remove unused slot bindings.
* Use `if-let`, `with-bounding-rectangle*` where appropriate.
=> Menu: fixes and cleanup

Extensions/fonts/freetype.lisp
The function font-glyph-dx did not have an applicable method when
used with a freetype font. Fixes #846
=> Freetype: Fix crash due to missing method

Backends/CLX/medium.lisp
This fixes #637 inside McCLIM instead of relying on a cache inside CLX.
=> Cache the bit depth for drawables.

Libraries/Drei/views.lisp
Fixes #678 and fixes #672
For context see above issues.
To try this in Climacs:
1) `(ql:quickload 'climacs)`.
2) `(climacs:climacs)`
3) Open a text file with `C-x C-f`. Press `C-x h` to select all region.
4) run `M-x tabify-region`, and save with `C-x C-f`.
You might want to inspect file in Emacs with `M-x whitespace-mode`. with this PR `tabify-region` and `untabify-region` should work without errors in Climacs.
=> Drei/views.lisp : space width is zero, use advance-width instead

Core/clim-basic/clim-basic.asd, Core/clim-basic/design.lisp, Core/clim-basic/geometry/regions.lisp
Before this change, the compile and load order of design.lisp and regions.lisp was not explicitly specified and loading design.lisp first lead to a warning due to `+identity-transformation+` not being defined yet.
Generally speaking, the geometry module (including `regions.lisp`) is more fundamental and should be compiled and loaded first. The only obstacle were `+{no,every}where+`, `{no,every}where-mixin` which are defined in `design.lisp` but initialized in `regions.lisp`. To allow compiling and loading `regions.lisp` first (and avoid the definition and initialization of `+{no,every}where+` in distinct places), `+{no,every}where+` and `{no,every}where-mixin` are now defined in `regions.lisp`.
=> Sort out dependency issues between design.lisp and regions.lisp

Backends/CLX/fonts.lisp, Core/clim-basic/medium.lisp, Extensions/fonts/freetype.lisp, Extensions/render/backend/port.lisp, Tests/util/test-page.lisp
This fixes minor problems introduced in b2e1930b.
* The `text-style-mapping` can be specialized to `standard-text-style` instead of checking the type in the body. It can also be written more concisely using `alexandria:ensure-gethash`.
* One of the `text-style-mapping` calls in the freetype backend lacked the `clim:` package prefix.
* Indentation fixes.
* Test `stream-character-width` in the `print-test-page` test function.
=> Fixes for the TEXT-STYLE-TO-FONT removal

Core/clim-basic/utils.lisp
Macro with-output-to-output-record is not defined until later (so when
it is compiled it is assumed to be a function and a warning is
signaled). Use invoke-with-output-to-output-record which is already
declared. Fixes #893.
=> utils: parse-space: use function instead of a macro

Core/clim-basic/windowing/sheets.lisp
This provides a default implementation for
%invalidate-cached-device-regions so that the application will not
crash even if a sheet does not specialise this method.
Fixes #895
=> Implement %invalidate-cached-device-regions

Core/clim-core/dialog.lisp
#654 describes problems with the keybindings for accepting-values, and so I've made an attempt at fixing one of them.
No command for OK existed, so I created one. It is bound to `C-[` and `M-RET`. `M-RET` was added based on @lokedhs's suggestion that it is more intuitive.
Exit works like you'd expect OK to. I haven't changed this since the OK button uses the command to confirm, and some people might have gotten used to pressing `C-]` to confirm.
This is my first contribution to McCLIM, so please let me know if I've done something wrong.
=> Fix accepting-values keybindings

Core/clim-basic/utils.lisp
*This* turns out to be all that is needed for @armedbear to compile McCLIM master successfully.
Supersedes <https://github.com/McCLIM/McCLIM/pull/909>.
=> abcl: patch for getenv

Core/clim-core/frames.lisp
Old version of FRAME-DISPLAY-POINTER-DOCUMENTATION-STRING didn't
trigger the redisplay of the pointer-documentation-pane so the string
were not visible (e.g documentation in some scigraph commands).
----
#
=> display string in pointer-documentation-pane

Apps/Listener/file-types.lisp
If in a pathname there is a #\Space character it is necessary to
escape it with a backslash when the view command string is generated.
----
#
=> Listener: open pathnames with #\Space

Apps/Listener/dev-commands.lisp
It can often be useful to be able to quickly get the documentation of
a class. This command takes a class name and prints the documentation
string if one is available. It also properly handles cases where either
the class does not exist or the documentation string does not exist.
=> Listener: Add command COM-SHOW-CLASS-DOCUMENTATION.

Backends/CLX-fb/frame-manager.lisp, Backends/CLX/frame-manager.lisp, Backends/Null/frame-manager.lisp, Core/clim-core/panes.lisp, package.lisp
Until now each backend had their own ad-hoc method. Now we introduce a
common protocol which unifies behavior and allows other clients to
resolve a pane-type to a concrete class. New function is called
find-concrete-pane-class and is specialized on a frame-manager.
This approach saves us some mess in clx's frame-manager
implementation.
=> make-pane-1: add a new protocol to resolve abstract pane names

Core/clim-basic/protocol-classes.lisp, Core/clim-core/clim-core.asd, Core/clim-core/gadgets.lisp, Core/clim-core/gadgets/abstract.lisp, Core/clim-core/gadgets/base.lisp, Core/clim-core/gadgets/concrete.lisp, Core/clim-core/gadgets/drawing-utilities.lisp, Core/clim-core/gadgets/mixins.lisp
Put gadgets in a separate module. It is a self-contained changed factored out from a local branch for adding themes to frame managers. No functional change is expected – all changes were a typical cleanup without adding or removing interfaces. Only slots from the protocol class gadget has been moved to a basic-gadget.
=> Cleanup split gadgets

Backends/common/fonts.lisp, Backends/common/mcclim-backend-common.asd, Backends/common/test/fonts.lisp, Backends/common/test/package.lisp, Core/clim-basic/drawing/medium.lisp
*DEFAULT-TEXT-STYLE* may change and then mapping would be invalid.
Also:
- add a method to the function TEXT-STYLE-COMPONENTS specialized on
DEVICE-FONT-TEXT-STYLE returning (values :device :device :device);
method must be defined for all subclasses of text-style
- be more robust in parse-text-style* by returning
DEVICE-FONT-TEXT-STYLE as is; this text style is always considered
to be fully specified.
=> text-style-mapping: do not cache partially specified text styles

Core/clim-basic/extended-streams/text-selection.lisp
Without this change, instances of `text-selection-mixin` rerouted certain pointer events to `eos/shift-{release,drag}` as soon as the shift modifier was active. This behavior was wrong because it did not consider whether a text selection activity was in progress or not (which is indicated by the `dragging-p` slot of the pane and thus easily checked).
This will fix #961
=> Fix drag and drop while shift modifier is active

Backends/PDF/sheet.lisp, Backends/PostScript/sheet.lisp, Core/clim-basic/drawing/medium.lisp
This commit implements a method for the generic function defined in
the CLIM specification MEDIUM-DRAWABLE specialized on BASIC-MEDIUM.
The methods of MEDIUM-DRAWABLE specialized on POSTSCRIPT-MEDIUM and
PDF-MEDIUM are removed because they are no more necessary.
=> medium-drawable method for basic-medium

Apps/Clouseau/src/application.lisp, Apps/Clouseau/src/formatting.lisp, Apps/Clouseau/src/navigation/navigation.lisp, Apps/Clouseau/src/objects/array.lisp, Apps/Clouseau/src/objects/class.lisp, Apps/Clouseau/src/objects/instance.lisp, Apps/Clouseau/src/package.lisp, Apps/Clouseau/src/pane.lisp, Apps/Clouseau/src/place-formatting.lisp, Apps/Clouseau/src/place.lisp, Documentation/Manual/Texinfo/chap-inspector.texi, Documentation/Manual/Texinfo/inspector-example.lisp
1. Export classes and adjust documentation so that the Clouseau tutorial works again
2. Cleanup inconsistencies between `ensure-place` and `formatting-place` (as pointed out by @robert-strandh )
3. When printing slot names, omit package if it is the same as the "context package"
4. Better support for reinitialization of Clouseau structures
5. Prettier and more readable history
=> Clouseau Improvements

Core/clim-core/presentations.lisp
It is allowed for define-presentation-type to assume, that class has
been already defined (that is -- defclass must be evaluated before the
matching define-presentation-type). McCLIM patches defclass to store
information about defined classes at compilation time to allow them to
be defined both as top-level forms in the same file without additional
eval-when by some implementations which use that information; add ECL
to this set.
=> presentations: use information from the patched defclass on ecl

Core/clim-basic/clim-basic.asd, Core/clim-basic/setf-star.lisp, Tests/setf-star.lisp, mcclim.asd
With this change, generic function lambda list is correctly parsed and
is used to construct the correct defsetf lambda list.
Closes #802, #96.
=> Correctly parse defgeneric* lambda list

Core/clim-basic/extended-streams/recording.lisp, Core/clim-basic/extended-streams/stream-output.lisp, Core/clim-basic/extended-streams/text-formatting.lisp, Core/clim-basic/utils.lisp, Examples/misc-tests.lisp, Tests/utils.lisp
Previous default value was 80 characters wide, while stream has its
own line width. It is better default, because when text-margins are
specified then filling-width does not ignore them unless explicitly
told to.
=> filling-output: better default for fill-width

Tests/package.lisp
Recently exported symbol clim:test caused a symbol name conflict with
fiveam:test symbol because clim-tests USE both packages. Use
shadowing-import to rectify that.
=> tests: fix the package conflict between clim-tests and clim

Core/clim-core/frames.lisp
The comment above the function said it would be a better way of doing things, and I agree. The only thing I'm uncertain about is whether my implementation of the check is as clean as it could be; the named block within the loop that exists only so the `frame-layout-changed` handler can return from it to continue to the next iteration.
=> Move FRAME-EXIT check into RUN-FRAME-TOP-LEVEL

Core/clim-core/menu-choose.lisp, Core/clim-core/presentations/presentation-type-functions.lisp, Core/clim-core/standard-presentations.lisp, Documentation/Specification/presentation-types.tex, Tests/presentations/presentation-types.lisp
Presentation types BLANK-AREA and MENU-ITEM had no implementation of
the presentation method PRESENTATION-TYPEP. Default method was
returning mistakenly T and recent fix to that revealed that issue.
=> presentation-typep: implement missing methods

Core/clim-basic/extended-streams/recording.lisp, Core/clim-basic/utils.lisp, Extensions/bezier/bezier.lisp
It is not generally correct or safe to store the string passed to `medium-draw-text*` in the created `draw-text-output-record` instance:
* The string could be changed after the `medium-draw-text*` call:
```common-lisp
(loop with buffer = (make-string 10)
do (fill-buffer buffer)
(draw-text* stream buffer ...))
```
* The string could have dynamic extent in which case storing it in the `draw-text-output-record` would lead to out-of-extent accesses:
```common-lisp
(let ((string ...))
(declare (dynamic-extent string))
(draw-text* stream string ...))
```
This is an actual problem which leads to bad crashes for seemingly innocent things like `(princ 5 <output-recording-stream>)` in recent SBCL versions.
The fix implemented in this change lets `generate-medium-recording-body` handle an argument …
=> Fix out-of-extend use in DRAW-TEXT-OUTPUT-RECORD

Core/clim-core/menu-choose.lisp
This is only visible in the expansion of the `define-presentation-method` form but the `type` argument is used. As a result, the `ignore` declaration is incorrect which causes a warning in e.g. SBCL.
=> menu-choose: fix IGNORE declaration

Backends/CLX-fb/package.lisp, Extensions/render/image.lisp, Extensions/render/types.lisp, Extensions/render/utilities.lisp
This gets the drawing benchmark in "red rectangle" mode to 466 on my machine.
Change details:
* Package cleanup
* New types `image-{dimension,index-displacement}`
* Declare types.
* Disregard `clip-region`, in particular the per-pixel `region-contains-position-p` check, if the image region is entirely contained in it.
* Instead of unconditionally and fully updating the alpha value and the ink-based color values once per pixel, only perform the necessary computations and do not recompute unchanged quantities.
* Depending on the flipping and blending mode, skip unnecessary flipping and blending computations.
=> Major performance improvements in `fill-image`

Core/clim-basic/decls.lisp, Core/clim-core/panes.lisp
Before this change, every `(setf label-pane-label)` call caused a `layout-frame` call for the containing frame. In applications like the clim-fig example that update a label within `tracking-pointer`, this behavior caused performance issues and could cause re-painting problems in other panes (as could be seen in the clim-fig example with e.g. the clx-fb backend).
After this change, the label pane checks whether its space requirements have actually changed before calling `change-space-requirements`.
=> panes: LABEL-PANEL does not cause unnecessary LAYOUT-FRAME calls

Core/clim-basic/extended-streams/stream-input.lisp, Core/clim-basic/windowing/input.lisp, Core/clim-core/frames.lisp, Core/clim-core/presentations/translators.lisp, Core/clim-core/presentations/typed-input.lisp, Tests/input-streams.lisp, mcclim.asd
This pull request separates the event queue and the stream's input buffer. It is a preliminary step towards cross-frame presentation sensitivity.
=> Refactor input streams new

Core/clim-core/presentations/presentation-types.lisp, Core/clim-core/presentations/translators.lisp
This PR improves record-presentation-type to not error when get-ptype-metaclass is called at compile time and makes presentation translators error when the presentation type does not exist when initializing the translator.
=> Presentation types #4

Core/clim-core/table-formatting.lisp, Documentation/Specification/table-formatting.tex
* All `formatting-*` macros are specified to accept a `record-type` keyword argument and to allow other keyword arguments. This is almost certainly intended as a mechanism for passing initargs in case non-default record types are used. To make this mechanism work consistently across all macros:
* Use `apply` with `invoke-with-new-output-record` and the passed initargs in all `invoke-with-*` functions
* Use `&allow-other-keys` in all macros.
* Use `gen-invoke-trampoline` in all macro.
* Check initargs which are passed as keyword argument in `formatting-*` at macroexpansion-time when possible.
=> Better keyword checking and processing in table formatting

Core/clim-basic/extended-streams/stream-input.lisp, Core/clim-core/builtin-commands.lisp, Core/clim-core/commands.lisp, Core/clim-core/input-editing.lisp, Core/clim-core/standard-presentations.lisp, Libraries/ESA/esa.lisp, Tests/input-editing.lisp
This commit solves the regression where reading sequences were not working.
=> seis: remove character input methods

Core/clim-core/panes/composition.lisp
The two `box-layout-mixin/xically-allocate-space` methods lay out child panes sequentially, keeping track of the offset in the major dimension. This offset is increased according to the allotted widths of children as well as the spacing between children. Before this change, a `+fill+` client (which does not have a pane and thus does not need spacing) caused one additional unit of spacing to be added to the offset, potentially pushing the final "real" client out of the allocated region.
The following screenshot shows the issue when adding `:x-spacing 8` to the `horizontally` containing the push buttons in the file selector demo:
=> Fix box-pane and rack layouts with +FILL+ and spacing

Core/clim-core/commands/tables.lisp, Documentation/Manual/LaTeX/chap-using-command-tables.tex, Documentation/Manual/Texinfo/reference-manual.texi
The specification entry for `make-command-table` explicitly says:
>  make-command-table does not implicitly include CLIM's global command
>  table in the inheritance list for the new command table.
=> commands: MAKE-COMMAND-TABLE does not add GLOBAL-COMMAND-TABLE

Core/clim-basic/extended-streams/stream-input.lisp
I verified with CMUCL 21D Unicode and SBCL 2.0.6 that `string-stream` is now a direct superclass of the respective string input stream class.
=> stream-input: drop STRING-STREAM hack for SBCL and CMUCL

Core/clim-core/frames/define-application-frame.lisp, Core/clim-core/frames/frames.lisp, Core/clim-core/panes/layout-protocol.lisp
* Ignore unused variable
* Translate `:resize-frame` option to `define-application-frame` into a default initarg
=> Fixup for layout changes

Core/clim-core/frames/frames.lisp
According to the specification entry for `redisplay-frame-panes', the function calls
> `redisplay-frame-pane` on each of the panes in frame *that are visible* in the current layout.
Reasons for not being visible in the current layout include
* Not being part of the current layout. This is covered automatically and already worked before this change since our implementation traverses sheets from the top-level sheet of the frame.
* Not being enabled or having an ancestor that is not enabled. The specification entries for `[setf] sheet-enabled-p` state:
> Note that a sheet is not visible unless it and all of its ancestors are enabled.
This was not previously handled and is now handled by ignoring sheets for which `sheet-viewable-p` returns false.
The practical consequence of this change is …
=> REDISPLAY-FRAME-PANES checks "viewability" of sheets

Examples/graph-formatting-test.lisp
* so that it works for other lisps than sbcl
=> Replace sb-mop:class-direct-subclasses by closer-mop:class-direct-subclasses

Core/clim-basic/drawing/graphics.lisp, Core/clim-basic/geometry/transforms.lisp
* While running climdemo `clim-fig` with `Arrow` I get an `arithmetic-error` using clasp
* The problem stems from `atan*` which is called like (atan* 0 0.0). This finally calls (atan 0.0 0) which returns `#<single-float quiet NaN>`
* According to the table in http://www.lispworks.com/documentation/HyperSpec/Body/f_asin_.htm#atan:
`y = 0        x = 0        Origin           undefined consequences` this seems to be undefined behavior, at least when -0 is not supported
* Therefor I propose to directly return 0.0 in this case
* tested in clasp and sbcl
=> Climdemo Clim-Fig Arrows: Avoid undefined behavior for (atan 0 0)

Core/clim-core/panes/stream-panes.lisp
In the generated `make-clim-*-pane` functions, remove default value of keyword parameters since they were never passed to `MAKE-CLIM-STREAM-PANE`.
=> Use macro to define MAKE-CLIM-*-PANE and cosmetic changes

Libraries/Drei/drei-clim.lisp, Libraries/Drei/input-editor.lisp
This method is used to process input editing commands and is not prepared to
work with pointer events. Most notably esa-read-gesture which is called from
read-gestures-and-act does not recognize them as a proper gesture and waits
until some key is pressed (indefinetely). Fixes #1080.
=> drei: stream-process-gesture: ignore pointer events

Core/clim-basic/extended-streams/pointer-tracking.lisp, Core/clim-basic/extended-streams/stream-input.lisp, Core/clim-basic/windowing/events.lisp, Core/clim-basic/windowing/ports.lisp, Core/clim-core/frames/frames.lisp, Core/clim-core/gadgets/concrete.lisp, Core/clim-core/panes/composition.lisp, Core/clim-core/panes/stream-panes.lisp, Libraries/ESA/esa.lisp, Tests/input-streams.lisp, package.lisp
This PR is a replacement for #606. Slider improvements were merged earlier, so they are not backported, and scroll-bar handle-event method is not backported because I don't personally think it is a good idea -- it is not consistent with existing toolkits.
- recognize wheel-left and wheel-right pointer gestures
- add a pointer-scroll gesture
- add named gestures scroll-up and scroll-down
- clim-stream-pane does not scroll the sheet if the gesture has associated translator
- mouse-wheel-scroll-mixin forwards the pointer-scroll-event if it has modifiers
=> Replace 606

Core/clim-core/commands/processor.lisp
Before this change, the `accept` method for the `command` presentation type, when `maybe-replace-input` is invoked via a presentation click, did not check whether the translator returned the :echo nil option in its third argument.
Test program:
``` common-lisp
(clim:define-presentation-type thing ()
:inherit-from t)
(clim:define-application-frame test ()
()
(:pane
(clim:vertically ()
(clim:make-pane :application :display-function (lambda (frame pane)
(clim:present 1 'thing)))
(clim:make-pane :interactor))))
(define-test-command com-doit
((thing thing :gesture (:select :echo ni))))
(clim:run-frame-top-level (clim:make-application-frame 'test))
```
=> Commands processor respects :ECHO option returned by translator

Core/clim-core/commands/commands.lisp, Core/clim-core/commands/processor.lisp, Core/clim-core/commands/tables.lisp, Core/clim-core/dialog.lisp, Documentation/Specification/commands.tex, Tests/commands.lisp
This PR addresses number of issues encountered when working with menus and keystroke accelerators. Part of said issues are a result of inconsistent specification - it is also modified. The "commands" test suite is updated accordingly (with other fixes along the way).
=> command table menu rewrite

Backends/CLX-fb/frame-manager.lisp, Backends/CLX-fb/package.lisp, Backends/CLX/frame-manager.lisp, Backends/CLX/port.lisp
* Cosmetic changes, untabifying and file headers
* Also share a single implementation of `maybe-mirroring` between CLX and CLX-fb
* Simplify mirroring decision logic
* Simplify CLX server path parsing
=> Fix name collisions of ad-hoc classes generated by CLX backend for mirroring

Backends/CLX-fb/port.lisp, Backends/CLX/port.lisp, Backends/Null/port.lisp, Backends/PDF/sheet.lisp, Backends/PostScript/package.lisp, Backends/PostScript/sheet.lisp, Backends/RasterImage/port.lisp, Backends/RasterImage/rgb-port.lisp, Core/clim-basic/windowing/ports.lisp, Extensions/fonts/freetype.lisp, Extensions/fonts/xrender-fonts.lisp, package.lisp
Introduced change is backward-compatible (fallback method regresses back to symbol plist).
=> New mechanism for looking up the port

Libraries/Drei/basic-commands.lisp
After a change which caused the shift key to be treated as a regular modifier key, the self-insertion command will not trigger for shifted space anymore. This fix adds a new command that simply inserts a space and is bound to Shift-Space.
=> Make Shift-Space insert a space in Drei buffers

Libraries/Drei/drei-redisplay.lisp
The GTK backend only redraws the window content when FINISH-OUTPUT
is called, so this fix adds this call to Drei.
=> Call FINISH-OUTPUT after a Drei buffer have been updated

Extensions/Franz/franz.lisp
Commit 5bc9b44b simplified DRAGGING-DRAWING but introduced a bug: the
the drawing is not visible during the dragging and it is visible
at the end. The required behaviuor is the opposite, the drawing must
be visible during the dragging and must be erased at the end.
This commit fix this. To test try in the listener the following
functions that use DRAGGING-DRAWING:
CLIME:POINTER-PLACE-RUBBER-BAND-LINE*
CLIME:POINTER-INPUT-RECTANGLE*
=> franz: fix DRAGGING-DRAWING

Backends/GTK/mcclim-gtk.asd, Backends/GTK/medium.lisp, Backends/GTK/pango-updates.lisp, Backends/GTK/port.lisp
With logging now all the long-living Cairo and Pango objects return to a constant reference count.
=> Better Cairo and Pango Cleanup

Core/clim/text-editor-gadget.lisp
Obviously someone already removed :scroll-bars from the drei editor.
Every application that wanted to start a :text-editor pane failed
with the error about an unknown option keyword :scroll-bars.
Removing that fixes the error.
=> fixes the text-editor

Core/clim-core/commands/tables.lisp, Core/clim-core/gadgets/menu.lisp
Without this fix a command table inherit the menu-item of the ancestors
also when `:inherit-menu` is `:keystrokes`
=> command-tables: fix the inherited menu items

Core/clim-core/bordered-output.lisp
Before this change, the styles `:underline` and `:crossout` searched the output record to which the style is applied for child output records of type `text-displayed-output-record`.
However, in some cases relevant children are of type `draw-text-output-record`.
To reproduce the problem:
1. Start demodemo
2. Start Drawing Tests
3. Enable the "side-by-side view with the renderer output" option
4. Select the Text » Underlining or Text » Crossing out test
5. Note that the text decorations do not appear in the output of the render backend
=> Fix bordered output styles :UNDERLINE and :CROSSOUT

Core/clim-basic/extended-streams/pointer-tracking.lisp
This PR fix the handling of keyboard events during the tracking of the pointer.
This PR supersedes the PR #1119 following the suggestion of dkochmanski of using with-input-focus.
Fix: #1118
=> tracking-pointer: keyboard events

Core/clim-core/commands/processor.lisp, Core/clim-core/commands/tables.lisp
The spec (26.6.1) say that COMMAND presentation type represent
commands  accessible in COMMAND-TABLE presentation parameter and enabled
in *APPLICATION-FRAME*. The last requirement was not checked before this commit.
The spec (27.4) say that in LOOKUP-KEYSTROKE-COMMAND-ITEM
"only keystrokes that map to an enabled application command will be
matched."
In this way  disabled commands aren't executed.
Fix #1144 issue
=> Don't execute a disabled command

Core/clim-basic/extended-streams/stream-output.lisp
Current clasp fails with the address-book demo displaying the names of the addresses. The reason is obviously that `(write-string "Scott McKay")` returns nil, while present expects a string.
This happens since 
`(defmethod stream-write-string ((stream standard-extended-output-stream) string
&optional (start 0) end)...` returns nil
Looking at the documentation for stream-write-string it says:
```lisp
— Generic Function: sb-gray:stream-write-string stream string &optional start end
This is used by write-string. It writes the string to the stream, optionally delimited by start and end, which default to 0 and nil. The string argument is returned.
````
=> stream-write-string is supposed to return the string passed to:

Core/clim-core/frames/frames.lisp
The CLIM Specification says that GRAFT is defined for application
frames but before this commit the method wasn't defined.
=> frames: graft method for application-frame

Core/clim-core/frames/frame-managers.lisp
ADOPT-FRAME-PANES creates (when required) the menu and
pointer-documentation pane, but the frame-panes weren't updated
accordingly. In this way the function UPDATE-FRAME-PANE-LISTS didn't
find the pointer-documentation pane that therefore didnt't work.
=> frame-panes and pointer-documentation fix

Core/clim-core/input-editing.lisp, Core/clim-core/presentations/standard-presentations.lisp
This commit changes the function accept-using-read to accept default and
default-type and return them when the token is an empty input. Fixes #839.
=> accept: change a default to honor the default value

Core/clim-basic/extended-streams/stream-output.lisp
In modern typesetting an em is often just the absolute font size. This does not look good in pretty printing where using the traditional definition of the width of an uppercase "M" is better.
Also, the functions `pprint-indent` and `pprint-tab` allow Real-valued column values. The Gray stream protocol does not make any statement about the return value of `stream-line-column`. Returning a Real-valued column number will make proportional typesetting have better alignments.
=> Use uppercase M for em conversion and allow real column values

Core/clim-core/dialogs/menu-choose.lisp
For the specification if presentation-type is supplied, the visual
representation is produced by present of the menu item with that
presentation type.
Fix #1252
=> frame-manager-menu-choose: presentation-type keyword

Examples/address-book.lisp
Context:running the Examples/address-book.lisp application.
Without this setting, with SBCL on Linux, Entering information for the
"Name" field and pressing ENTER takes you to the "Address" field, but
the "Name" field becomes blank.
With this setting the already entered values continue to be displayed.
=> Add :resynchronize-every-pass t to address book accepting-values

Core/clim-core/commands/processor.lisp
LOOKUP-KEYSTROKE-COMMAND-ITEM may return the gesture if no command can be found
under the keystroke. We don't want to pass a gesture to ENSURE-COMPLETE-COMMAND
so just in case we check the result. This allows associating keystrokes with
arbitrary actions with add-keystroke-to-command-table :function.
=> core: read-command-using-keystrokes: sanitize the accelerator result

Core/clim-core/panes/stream-panes.lisp
The implementation was wrong. From the specification window-erase-viewport:
> Returns two values, the x and y position of the top-left corner of the CLIM
> stream pane window's viewport. If the window is not scrollable, this will return
> the two values 0 and 0.
=> window-viewport-position

Core/clim-core/commands/tables.lisp
For the specification COMMAND-ACCESSIBLE-IN-COMMAND-TABLE-P must
return the command table in which the command was found or NIL if the
command was not found.
Before this commit it return T or NIL.
With this commit also COMMAND-PRESENT-IN-COMMAND-TABLE-P return the
command table or NIL. I think this adhere to the specification where
is written that COMMAND-PRESENT-IN-COMMAND-TABLE-P returns true if the
command is present in the command table but the specification doesn't
say that it must return T.
=> command-accessible-in-command-table-p: specification conformance

Core/clim-core/frames/frame-managers.lisp
When there is menu or pointer-documentation-pane in a frame the top
level vrack layout pane was created using MAKE-INSTANCE instead of
MAKE-PANE-1, in this way it was created an instance of the abstract
class and not an instance of the concrete class choosed by the frame
manager.
=> frame-managers: use make-pane-1 instead of make-instance

Core/clim-core/presentations/typed-output.lisp
In format-items the default for printer cannot be provided in the lambda list
otherwise when the actual printer function is constructed in the let
form the case when presentation-type is supplied and printer isn't
supplied is never selected.
=> format-items: fix default printer

Core/clim-core/frames/frame-managers.lisp
MAP-OVER-FRAMES must always return NIL also when FRAME-MANAGER keyword argument is provided.
Otherwise, for example, FIND-APPLICATION-FRAME doesn't work with FRAME-MANAGER keyword argument provided.
=> map-over-frames: always return nil

Backends/CLX/frame-manager.lisp
The xwindow is in the variable WINDOW and not MIRROR
=> fix clx-frame-manager adopt-frame for :dock frame
