package.lisp

multiprocessing: cmu: bt supports cmu

---

Extensions/looks/mcclim-looks.asd

looks: pixie: don't activate by default

---

Core/clim-basic/clim-basic.asd
Core/clim-basic/decls.lisp
Core/clim-basic/recording.lisp

Fixed setf* dependencies as well.

Move CLIM declarations to decls.lisp

---

Core/clim-core/panes.lisp

Solution provided by @gabriel-laddel. Fixes #32.

scroller-pane: fix default-initargs

---

Backends/CLX/medium.lisp
Core/clim-basic/ports.lisp
Core/clim-basic/repaint.lisp
Core/clim-basic/sheets.lisp
Extensions/fonts/mcclim-fonts.asd
Extensions/fonts/xrender-fonts.lisp
Extensions/layouts/mcclim-layouts.asd
Extensions/looks/mcclim-looks.asd

A few bug fixes and Quicklisp patch

preliminary patches for mirroring

---

Backends/CLX/mcclim-clx.asd

truetype: enable truetype for all CLX

---

Backends/CLX-core/mcclim-clx-core.asd

backends: clx-core: fix loading

---

Core/clim-basic/clim-basic.asd
Core/clim-basic/design.lisp

This improvement was proposed by @deterministic-arts. Implementation
relies on trivial-garbage. Closes merge request #6.

color table: be weak on the values if possible

---

Extensions/fonts/fontconfig.lisp
Extensions/fonts/xrender-fonts.lisp

Reverts robert-strandh/McCLIM#67

Revert "Fix the mcclim-truetype on Debian 8.2.0"

---

Extensions/fonts/fontconfig.lisp
Extensions/fonts/xrender-fonts.lisp

See [PR 89](https://github.com/robert-strandh/McCLIM/pull/89)

Minor tweaks to the truetype font auto-configuration process

---

Backends/Standard/events.lisp
Backends/Standard/fm-sheets.lisp
Core/clim-basic/repaint.lisp
Core/clim-basic/stream-output.lisp

Hi Daniel,
I hope I had fixed two issues: #66, #94. I did not tested them deeply.
Alessandro

fix issues

---

Backends/CLX/mcclim-clx.asd
Extensions/fonts/mcclim-fonts.asd
Extensions/fonts/mcclim-native-ttf.lisp

make mcclim-fonts system independent from clx backend

---

Backends/RasterImage/graft.lisp
Backends/RasterImage/mcclim-raster-image.asd
Backends/RasterImage/medium.lisp
Backends/RasterImage/opticl.lisp
Backends/RasterImage/output-to-png.lisp
Backends/RasterImage/package.lisp
Backends/RasterImage/port.lisp
Backends/RasterImage/rgb-image.lisp
Backends/RasterImage/stream.lisp
Backends/RasterImage/top-level-pane.lisp
Documentation/Manual/LaTeX/chap-raster-image.tex
Documentation/Manual/LaTeX/mcclim.tex
Examples/clim-examples.asd
Examples/demodemo.lisp
Examples/drawing-tests.lisp
Extensions/render/design.lisp
Extensions/render/fonts.lisp
Extensions/render/mcclim-render.asd
Extensions/render/medium.lisp
Extensions/render/opticl.lisp
Extensions/render/package.lisp
Extensions/render/pixmap.lisp
Extensions/render/port.lisp
Extensions/render/prim-arc.lisp
Extensions/render/prim-path.lisp
Extensions/render/prim-text.lisp
Extensions/render/render.lisp
Extensions/render/rgb-image.lisp
Extensions/render/sheet.lisp

I improved the performance. 
There is a bug with the size of the font. Maybe you can solve it.
Alessandro

Raster Image Backend

---

Backends/RasterImage/output-to-png.lisp
Backends/RasterImage/package.lisp
Backends/RasterImage/port.lisp
Examples/drawing-tests.lisp
Extensions/render/design.lisp
Extensions/render/fonts.lisp
Extensions/render/medium.lisp
Extensions/render/opticl.lisp
Extensions/render/package.lisp
Extensions/render/pixmap.lisp
Extensions/render/port.lisp
Extensions/render/prim-path.lisp
Extensions/render/prim-text.lisp
Extensions/render/render.lisp
Extensions/render/rgb-image.lisp
Extensions/render/sheet.lisp

Hi Daniel,
I improved a bit the raster backend. 
Alessandro

raster backend: improve text rendering and flipping ink design

---

Libraries/Drei/lisp-syntax-swine.lisp

fix drei completions

---

Core/clim-core/presentation-defs.lisp

fix accepting or types

---

Core/clim-core/dialog.lisp
Examples/accepting-values-test.lisp
Examples/accepting-values.lisp
Examples/clim-examples.asd
Examples/demodemo.lisp

enhancement dialog

---

Extensions/fonts/fontconfig.lisp

Add Window's system font directory; also ensure you have dejavusans installed, for this to work correctly

fontconfig: windows fix

---

Core/clim-basic/regions.lisp
Core/clim-basic/transforms.lisp

Translate german comments in regions.lisp and transforms.lisp.

---

Core/clim-basic/regions.lisp
Core/clim-basic/transforms.lisp

Also fix erranous "horner scheme" -> "horner's method"

Delete german comments.

---

Extensions/bitmap-formats/bitmaps.lisp

Fix for https://github.com/robert-strandh/McCLIM/issues/167

Don't throw an error when trying to load images with a single channel

---

Backends/RasterImage/output-to-png.lisp

mcclim-render::image-sheet-image -> image-mirror-image

---

Examples/drawing-tests.lisp
Extensions/bezier/bezier.lisp
Extensions/bezier/package.lisp

Added relative-to-absolute-coord-seq and some more bezier drawing tests

More bezier stuff

---

Extensions/bezier/bezier.lisp

* remove slots that are either unused or poorly used. It's not at all
clear to me that these are supposed to do anything.
@robert-strandh can you review this one? This stuff seems like cruft to me, but perhaps you're using it. thanks!

remove transformation and original-region slots

---

Core/clim-core/graph-formatting.lisp
Core/clim-core/panes.lisp
Core/clim-core/table-formatting.lisp
Examples/misc-tests.lisp

#174 
I think that it is a bad idea changing the user space preferences.

using change-space-requirements instead of fit-pane-to-output

---

Core/clim-core/gadgets.lisp

Issue #144.
PS: The look and feel of several apps changes.

set max-width/height to +fill+

---

Backends/CLX/medium.lisp
Extensions/bezier/bezier.lisp

These changes fix the with-clx-graphics macro and improve bezier drawing. see commit logs for details.

with-clx-graphics macro and bezier drawing fixes

---

Core/clim-core/frames.lisp
Core/clim-core/menu.lisp
Core/clim-core/panes.lisp

For #218.
PS: It modifies a macro! You need to clear your cache.

fix setf of frame-command-table

---

Core/clim-core/panes.lisp

In my last pr I have broken 2 demo apps: Puzzle and Draggable Graph. 
I fix the problem.

fix compose-space with :compute values

---

Examples/drawing-tests.lisp

Issue #225  + same new features.

improve drawing-tests

---

Backends/CLX/medium.lisp

Issue #228.
It solve the recursive lock error when the debugger is invoked.

fix locking position

---

Core/clim-core/input-editing.lisp

fix clear completition record

---

Core/clim-basic/repaint.lisp

fix effective region in the repaint protocol

---

Core/clim-core/panes.lisp

fix compose-space with :compute requirement

---

Core/clim-basic/recording.lisp

* Fixes PostScript output with draw-rectangles*, which was totally
broken before.
* also, may fix Drawing Test "04) Rectangle Basic"

Added output recording code for draw-rectangles*

---

Apps/Listener/dev-commands.lisp

fix contents of

---

Backends/PDF/class.lisp
Backends/PDF/clim-pdf.asd
Backends/PDF/graphics.lisp
Backends/PDF/package.lisp
Backends/PDF/paper.lisp
Backends/PDF/sheet.lisp
Backends/PostScript/class.lisp
Backends/PostScript/clim-postscript-font.asd
Backends/PostScript/clim-postscript.asd
Backends/PostScript/font/afm.lisp
Backends/PostScript/font/clim-postscript-font.asd
Backends/PostScript/font/encoding.lisp
Backends/PostScript/font/font.lisp
Backends/PostScript/font/generate-metrics.lisp
Backends/PostScript/font/package.lisp
Backends/PostScript/font/standard-metrics.lisp
Backends/PostScript/graphics.lisp
Backends/PostScript/sheet.lisp
Core/clim-basic/decls.lisp
Core/clim-basic/recording.lisp
Core/clim-core/clim-core.asd
Examples/drawing-tests.lisp
Examples/pdf-test.lisp
Extensions/bezier/bezier.lisp
Extensions/bezier/mcclim-bezier.asd
mcclim.asd

I've cleaned up the clim-postscript-font package and its exports.

Cl pdf backend 2

---

Core/clim-core/presentation-defs.lisp
Libraries/Drei/drei-redisplay.lisp

Fixes https://github.com/robert-strandh/McCLIM/issues/265

Fix FIND-STROKE-CONTAINING-OFFSET & [$200] Interactor CLI prompt print problem

---

Core/clim-basic/stream-output.lisp

* previously, we would draw on the stream even if we were only recording.

check if stream-drawing-p before draw-... in stream-wrap-line

---

Core/clim-basic/protocol-classes.lisp

mixing spaces and tabs is evil

fix indentation

---

Examples/clim-examples.asd
Examples/demodemo.lisp
Examples/graph-toy.lisp

This adds my little graph toy to the mcclim demos package and the demodemo list of demos.

Add graph-toy to clim demos.

---

Documentation/Specification/drawing-options.tex
Documentation/Specification/extended-input.tex
Documentation/Specification/graphics.tex
Documentation/Specification/input-editing.tex
Documentation/Specification/menus.tex
Documentation/Specification/presentation-types.tex
Documentation/Specification/silica.tex
Documentation/Specification/text-styles.tex

Please take a look at these; not all might be usable as-is, because I'm not sure about some conflicting wording.
And no, I won't tell which changes, because if you don't know that you'll read every one carefully ;)
Thanks a lot.

Spelling and other small changes.

---

Backends/CLX/medium.lisp

can be tested with example code in #298

FIX #298: fix transparancy drawing problems in CLX backend

---

Documentation/Manual/LaTeX/chap-demos-and-applications.tex
Documentation/Manual/LaTeX/chap-first-application.tex
Documentation/Manual/LaTeX/chap-intro.tex
Documentation/Manual/LaTeX/ex1.lisp
Documentation/Manual/LaTeX/ex2.lisp
Documentation/Manual/LaTeX/ex2b.lisp
Documentation/Manual/LaTeX/ex2c.lisp
Documentation/Manual/LaTeX/mcclim.tex

Changes to Introduction and First Application chapters.

Changes to User Manual.

---

Libraries/Drei/lisp-syntax.lisp
Libraries/Drei/syntax.lisp

Drei minor fixes

---

Extensions/bitmap-formats/bitmaps.lisp

Note that this requires updated opticl-core and opticl packages.

support gray-alpha images

---

Core/clim-core/gadgets.lisp

This change is to address issue #311 .

Revise slider gadget to reflect the spec

---

Core/clim-basic/recording.lisp
Core/clim-basic/utils.lisp
package.lisp

1. Remove LAST1 utility function.
2. Use LAST-ELT from Alexandria (does the same thing and is more generic).
3. Update package declaration.

Use LAST-ELT from Alexandria

---

Examples/town-example.lisp

town-example: replace accepting-values with notify-user for output

---

Core/clim-core/describe.lisp

* bug fix for SBCL
* refactoring for less duplication and better extensibility 
* the rest is cosmetic

Improvements in describe.lisp

---

Apps/Debugger/clim-debugger.lisp

* Add pointer documentation pane
* Output causing condition as presentation to make it inspectable

Debugger improvements

---

Core/clim-basic/recording.lisp
Core/clim-core/bordered-output.lisp
Core/clim-core/table-formatting.lisp
Examples/clim-examples.asd
Examples/demodemo.lisp
Examples/misc-tests.lisp
Examples/package.lisp
Examples/tabledemo.lisp

- adds new test to misc tests
- adds new demo
- improves handling foreign records in formatting-table (most notably borders)
- clarifies some comments in the source code

Table formatting

---

Examples/dragndrop.lisp

FIX-398 : re-write the dragndrop example

---

Backends/CLX/input.lisp
Examples/clim-examples.asd
Libraries/Drei/input-editor.lisp
mcclim.asd

- handle mapping-notify to flush client keyboard cache (setxkbmap xxx works now)
- add (in-package asdf-user) to some asd files
- improve clim-examples.asd a tiny bit
- indentation fixes

small enhancements and mapping-notify handling

---

Core/clim-core/menu-choose.lisp

box sequence menu items as a whole, not individually

---

Backends/CLX-fb/mirrored-sheets.lisp
Backends/CLX-fb/package.lisp
Backends/CLX/frame-manager.lisp
Backends/CLX/mcclim-clx.asd
Backends/CLX/mirrored-sheets.lisp
Backends/CLX/package.lisp
Backends/CLXv3/frame-manager.lisp
Backends/CLXv3/mcclim-clxv3.asd
Backends/CLXv3/mirrored-sheets.lisp
Backends/CLXv3/package.lisp
Backends/RasterImage/package.lisp
Backends/RasterImage/top-level-pane.lisp
Backends/beagle/glimpse/glimpse-support.lisp
Backends/beagle/package.lisp
Backends/common/mirrored-sheets.lisp
Core/clim-basic/repaint.lisp
Core/clim-core/panes.lisp
Examples/clim-examples.asd
Examples/demodemo.lisp
Examples/hierarchy-tool.lisp

Second batch of cleanup (there will be the third one).
Also a new demo application useful for debugging mirrors.

simplify mirroring class hierarchy - pass2

---

Core/clim-basic/regions.lisp

Remove inappropriate method on bounding-rectangle

---

Apps/Scigraph/scigraph/draw.lisp
Backends/CLX/basic.lisp
Core/clim-basic/stream-input.lisp

The first commit fix issue #464.
The other two fix issue #467 and incidentally also #465

scigraph bug fix and new `stream-pointer-position`

---

Libraries/Drei/input-editor.lisp
Libraries/ESA/esa.lisp

Listener fix

---

Backends/PDF/graphics.lisp

properly (hopefully) transform text in medium-draw-text* in PDF backend.

transform text in PDF medium-draw-text*

---

Extensions/bezier/mcclim-bezier.asd

* mcclim-bezier-core -> mcclim-bezier/core
* mcclim-bezier-clx -> mcclim-bezier/clx

rename bezier ASDF systems

---

Examples/drawing-tests.lisp

Add a new polygon test and clean up some warning.

Drawing test cleanup

---

Backends/PostScript/font/font.lisp

* fix from jackdaniel for a couple PS font extent issues.

remove guard in psfont-text-extents, fix scale

---

Examples/colorslider.lisp

I changed the example so that it no longer uses not exported symbols.

Now it only uses exported symbols

---

Core/clim-basic/recording.lisp
Core/clim-basic/transforms.lisp
Core/clim/input-editing-drei.lisp
Libraries/Drei/packages.lisp

Supersedes #603. I've cherrypicked drei mixin changes without looking into it.

fix regression with transformations and add better specializations.

---

Extensions/fonts/freetype.lisp
Extensions/harfbuzz/src/functions.lisp
Extensions/harfbuzz/src/harfbuzz.lisp

The harfbuzz library was declared in more than one file

Harfbuzz lib fix

---

Core/clim-basic/input.lisp

We did check the queue for events and if not present we test for the timeout. If
timeout is not reached we process-next-event. This was wrong in a scenario,
where we have some events available on the backend but still not processed. We
do a similar preemptive check for event-queue-read-no-hang. Added checks have
timeout 0 so they don't block.

simple-event-queue: do preemptive checks where appropriate

---

Backends/common/fonts.lisp
Core/clim-core/gadgets.lisp
Core/clim-core/menu.lisp
Extensions/fonts/xrender-fonts.lisp

This supersedes the previous PR https://github.com/McCLIM/McCLIM/pull/655.

text-style and compose-space fixes

---

Core/clim-core/graph-formatting.lisp
Examples/draggable-graph.lisp

Update edges in addition to the node while dragging.

Feedback for edges in draggable graph example

---

Core/clim-basic/encapsulate.lisp

Following the suggetion of @slyrus I split PR #706 in three part. This is the second  part about encapsulating stream.
In this PR I add some methods and function to encapsulating-stream. This is not a systematic check of the encapsulating stream as suggested by @slyrus but I add only the function needed to display the Scigraph dialogs.

Encapsulating stream

---

Examples/drawing-tests.lisp

Please review it, I think it cover all requested changes.

drawing-tests: improve and refactor; 

---

Backends/common/fonts.lisp
Core/clim-basic/stream-output.lisp
Core/clim-basic/utils.lisp
Tests/tests.lisp

Word wrap is factored into a clim-agnostic utility. This is a first of a stream-output improvement patch series.

Refactor word wrap

---

Apps/Listener/dev-commands.lisp
Apps/Scigraph/dwim/extensions.lisp
Core/clim-core/describe.lisp

add more support to LispWorks development.

add minor support for lispworks.

---

Core/clim-core/presentation-defs.lisp

Fix a bug in definition of `sublist-alist` presentation abbreviation.

bug fix subset-alist definition

---

Examples/clim-fig.lisp

Actions get pushed onto the history, com-undo should behave like a
FIFO. The previous code undid the actions in the order they were performed.

clim-fig example: fix undo behaviour.

---

Core/clim-basic/graphics.lisp

Add missing contrasting dash patterns

---

Documentation/Manual/Texinfo/auxiliary-material.texi
Documentation/Manual/Texinfo/macros.texi
Documentation/Manual/Texinfo/mcclim.texi
Documentation/Manual/Texinfo/reference-manual.texi
Documentation/Manual/Texinfo/style-common.css

A few style improvements and a bit of cross-reference infrastructure. Required by the new Clouseau documentation.

More manual improvements

---

Apps/Clouseau/src/application.lisp
Apps/Clouseau/src/navigation/navigation.lisp
Apps/Clouseau/src/objects/array.lisp
Apps/Clouseau/src/objects/class.lisp
Apps/Clouseau/src/objects/function.lisp
Apps/Clouseau/src/objects/generic.lisp
Apps/Clouseau/src/objects/instance.lisp
Apps/Clouseau/src/objects/list.lisp
Apps/Clouseau/src/objects/sequence.lisp

This fixes a couple of small issues, cleans up a few things and improves the inspection of instances, slots and classes.

Improvements for new inspector

---

Backends/CLX-fb/package.lisp
Backends/CLX-fb/port.lisp
Backends/CLX/input.lisp
Backends/CLX/medium-xrender.lisp
Backends/CLX/medium.lisp
Backends/CLX/package.lisp
Backends/CLX/port.lisp
Backends/Null/medium.lisp
Backends/Null/port.lisp
Backends/common/fonts.lisp
Core/clim-basic/events.lisp
Core/clim-basic/graphics.lisp
Core/clim-basic/medium.lisp
Documentation/Manual/Texinfo/developer-manual.texi
package.lisp

Set of loosely related changes.

various fixes

---

Core/clim-core/gadgets.lisp

slider-pane: check if the slider is properly armed for release event

---

Apps/Listener/asdf.lisp
Apps/Scigraph/dwim/present.lisp
Apps/Scigraph/dwim/wholine.lisp

These fixes silence around three warnings in SBCL.

Small fixes for the listener and scigraph

---

Core/clim-core/panes.lisp

Also adds missing display-function. This is adapted from a patch from
Robert Swindells around 2009.
Fixes #366 .

title-pane : implement title-pane functionality

---

Core/clim-core/panes.lisp
Examples/clim-fig.lisp
package.lisp

See #605 for context.
An example to test:
```lisp
(eval-when (:compile-toplevel :load-toplevel :execute)
(unless (find-package "CLIM")
(ql:quickload 'mcclim)))
(in-package :clim-user)
(define-application-frame label-test ()
()
(:panes
(label :label-pane
:label "A Label")
(int :interactor :width 600))
(:layouts
(default (vertically () label int))))
(define-label-test-command (com-change-label :name t :menu t)
((new-label string))
(setf (clime:label-pane-label (find-pane-named *application-frame* 'label))
new-label))
(defun run-label-test ()
(run-frame-top-level (make-application-frame 'label-test)))
```
A sample run looks like:

Label pane

---

Examples/clim-fig.lisp

* Naively show final appearance while drawing a figure
* Add a gadget for choosing the line dashes style
* Disable/enable commands as appropriate (in addition to the corresponding buttons)

More clim-fig improvements

---

Core/clim-basic/encapsulate.lisp

As explained in the commit message, `invoke-with-temporary-page` should, like `invoke-with-drawing-options`, pass the *encapsulating* stream to the continuation (not the *encapsulated* stream). Otherwise code like
``` common-lisp
(with-encapsulating-stream (stream)
(formatting-table (stream)
...
(encapsulating-stream-stream stream)
...))
```
would fail because the value of the innermost `stream` binding would not necessarily be an encapsulating stream.
This is an alternative to the solution proposed in #874. I made sure it fixes #859 as well as the "Address Book" regression described by @admich in https://github.com/McCLIM/McCLIM/issues/859#issuecomment-538764398.

Implement INVOKE-WITH-TEMPORARY-PAGE like INVOKE-WITH-DRAWING-OPTIONS

---

Core/clim-basic/extended-streams/text-formatting.lisp
Core/clim-core/bordered-output.lisp
Examples/bordered-output-examples.lisp
Examples/drawing-tests.lisp
Tests/text-formatting.lisp
mcclim.asd

Supersedes #882. This branch is based on #886 so it should be reviewed after merging it.

Casual improvements

---

Extensions/fonts/fontconfig.lisp

Reported by vms14 on freenode.

Add font path for NetBSD.

---

Examples/bordered-output-examples.lisp
Examples/calculator.lisp
Examples/colorslider.lisp
Examples/coordinate-swizzling.lisp
Examples/demodemo.lisp
Examples/draggable-graph.lisp
Examples/dragndrop-translator.lisp
Examples/dragndrop.lisp
Examples/drawing-tests.lisp
Examples/flipping-ink.lisp
Examples/graph-toy.lisp
Examples/image-transform-demo.lisp
Examples/indentation.lisp
Examples/method-browser.lisp
Examples/misc-tests.lisp
Examples/patterns-overlap.lisp
Examples/patterns.lisp
Examples/presentation-test.lisp
Examples/render-image-tests.lisp
Examples/sliderdemo.lisp
Examples/stream-test.lisp
Examples/tabledemo.lisp
Examples/text-multiline-positioning.lisp
Examples/text-size-test.lisp
Examples/text-transformation-test.lisp
Examples/tracking-pointer.lisp
Examples/traffic-lights.lisp

Add (:menu-bar nil) to demos and tests that don't have menu bars.

---

Apps/Listener/file-types.lisp

The LISTENER reads mailcap files to associate applications to mime
types. In these files it is possible to use wildcard to match all
subtypes (e.g. "image/*"), but before this commit the LISTENER didn't
use these associations.
----
#

Listener: mime types with wildcard

---

Core/clim-core/panes.lisp
Examples/demodemo.lisp

* Support multi-line labels, demonstrate multi-line labels in `label-test` demo
* Handle labels changes better, in particular change space requirements if necessary
* Cleanup

LABEL-PANE improvements

---

Core/clim-basic/utils.lisp
Core/clim-core/frames.lisp

This pull request introduces a mechanism for updating existing frame instances when their frame class is redefined. Documentation and a new example are also included.

Preparation for automatic frame instance update on frame class redefinition

---

Backends/CLX/input.lisp
Backends/Null/package.lisp
Backends/Null/port.lisp
Core/clim-basic/windowing/input.lisp
Documentation/Specification/silica.tex

Improve specification and implementation of wait-function in process-next-event and event-queue protocol functions.

wait-function clarifications

---

Backends/CLX/fonts.lisp
Backends/Null/port.lisp
Backends/PostScript/font/font.lisp
Core/clim-basic/drawing/medium.lisp
Core/clim-core/frames.lisp
Examples/drawing-tests.lisp
Extensions/render/backend/port.lisp
Libraries/Slim/slim.lisp
Tests/text-styles.lisp
mcclim.asd

atomic fixes for a few issues reported lately. also a cosmetic improvement to slim library.

Fix various

---

Backends/CLX/port.lisp

I think I figured out why :clx-ttf didn't work in Windows

---

Core/clim-core/presentation-defs.lisp

This fixes completions for all types of pathnames.
This addresses the same issues as 954 which has been closed.
Currently if the pathname begins with ~/ (meaning start from my home directory)
the pathname will not complete;
Also If the pathname is a logical pathname and there
is a file in the directory that the pathname resolves to and that file's name
includes a character that is illegal for a logical pathname then the pathname
will not complete.
The original filename-completer function is now broken into 3 steps:
1) Given the string to be complered, figure out what directory is
implied.  This considers both logical pathnames and pathnames relative to the
home directory.
2) In that directory collect all the files whose names begin with the string.
If the pathname is a logical pathname …

Fix completion for logical pathnames

---

package.lisp

Export completion presentation type parameters and options

---

Apps/Clouseau/src/commands.lisp
Core/clim-core/presentation-drag-and-drop.lisp

Also fixes the problem of pointer documentation for drag and drop translators sometimes not being displayed.

A few improvements for Clouseau

---

Core/clim-basic/extended-streams/recording.lisp

The slots `start` and `end` have been removed from `draw-text-output-record` in ab85d944 but the methods generated by `(defrecord-predicate draw-text-output-record)` still tried to include them in the comparison.
To fix the issue, `defrecord-predicate` can now accept things that are keyword arguments but not slots and can also generate different comparison code for the slot and the argument cases.

recording: fix DEFRECORD-PREDICATE DRAW-TEXT-OUTPUT-RECORD again

---

Core/clim-basic/extended-streams/stream-output.lisp

Consider the following snippet:
(with-text-size (stream :huge)
(format stream "HEY1!"))
(fresh-line stream)
(format stream "HEY2!~%")
(format stream "HEY3!~%")
(format stream "HEY4!~%")
When the above code is executed, then FRESH-LINE caused advancing the cursor
vertically by the STREAM-CHAR-HEIGHT of the line with the size :HUGE), and did
not reset the STREAM-CHAR-HEIGHT, so after the line "HEY2!" a vertical
advancement was once again the STREAM-CHAR-HEIGHT line with the size :HUGE.
(with-text-size (stream :huge)
(format stream "HEY1!~%"))
(format stream "HEY2!~%")
(format stream "HEY3!~%")
The situation is similar, however it is slightly different: the newline is
called when a text style with the size :HUGE is still the context of
drawing. That illustrates, that we should not set …

seos: do not assume stream-char-height after a new line

---

Core/clim-core/input-editing.lisp
Core/clim-core/presentations/presentation-type-functions.lisp
Core/clim-core/presentations/translators.lisp
Examples/presentation-translators-test.lisp
Tests/presentations/presentation-types.lisp

This PR adds a special treatment for aggregate presentation types COMPLETE and SUBSET-COMPLETE to allow accepting types like (member 1 2 3). This PR is done on top of #1023.

Presentation Types #3

---

Core/clim-core/commands/processor.lisp
Core/clim-core/presentations/typed-input.lisp

fixes #955
fixes #967 
fixes #968

Replace 968

---

Core/clim-core/gadgets/concrete.lisp
Core/clim-core/panes/composition.lisp

* Fill bottom part of the sheet region/viewport region that is not covered by rendered items with the background ink.
* Change space requirements and repaint after `visible-items` is changed.
* Reset `items-origin` after `list-pane-items` is set.
* Remove unnecessary `(setf list-pane-items) :after` method. This method did three things, change space requirements, clear pane background and initiate a repaint, that are already done by the other methods.
* Efficiency improvements: do fewer things for every item: such as calling various readers and setting the text style
The previous `allocate-space` method called `move-and-resize-sheet` and `allocate-space` for the child pane before updating the scroll bars. That order resulted in `move-and-resize-sheet` using the old scroll bar values which, …

Fix repainting of GENERIC-LIST-PANE

---

Extensions/render/backend/medium.lisp
Extensions/render/cl-vectors/vectors-image-ops.lisp

* Fix bit twiddling in flipping ink implementation
* Use correct package for `medium-draw-circle*`

Small fixes for the render extension

---

Core/clim-core/frames/frames.lisp

This fixes a regression introduced in 96c3158f. Between 96c3158f and this change, when three or more frames ran in nested command loops and the outermost frame exited, both inner command loops handled the
`frame-exit` condition in the `handler-bind` clause. This caused multiple calls to `disown-frame` of which only the first succeeded.
To reproduce the problem, start demodemo, start three demos, then close the frame of the demo which has been started first.

Fix FRAME-EXIT for three or more nested command loops

---

Backends/CLX-fb/medium.lisp
Backends/CLX-fb/mirror.lisp
Backends/CLX-fb/mirrored-sheets.lisp
Backends/CLX-fb/package.lisp
Backends/CLX-fb/port.lisp
Backends/CLX/basic.lisp
Backends/CLX/clipboard.lisp
Backends/CLX/frame-manager.lisp
Backends/CLX/input.lisp
Backends/CLX/medium-xrender.lisp
Backends/CLX/medium.lisp
Backends/CLX/mirror.lisp
Backends/CLX/package.lisp
Backends/CLX/port.lisp
Backends/Null/port.lisp
Backends/RasterImage/output-to-image.lisp
Backends/RasterImage/package.lisp
Backends/RasterImage/rgb-port.lisp
Backends/RasterImage/test/output-to-image.lisp
Core/clim-basic/windowing/pixmap.lisp
Core/clim-basic/windowing/ports.lisp
Extensions/render/backend/medium.lisp
Extensions/render/backend/mirror.lisp
Extensions/render/backend/mirrored-sheet.lisp
Extensions/render/backend/pixmap.lisp
Extensions/render/backend/port.lisp
Extensions/render/package.lisp
Extensions/render/render/prim-text.lisp

Supersedes #1096 -- this pr is another set of changes towards cleaner backend definition abstraction.

Backend manual

---

Core/clim-basic/extended-streams/pointer-tracking.lisp
Core/clim-core/frames/frame-managers.lisp
Core/clim-core/frames/frames.lisp

Sparse fix

---

Backends/CLX/input.lisp
Backends/CLX/mirror.lisp
Core/clim-basic/windowing/events.lisp
Core/clim-basic/windowing/sheets.lisp
Core/clim-core/frames/frames.lisp
Core/clim-core/panes/composition.lisp
package.lisp

With this PR the frame state is updated when the frame state change due to user interaction with the  window manager.
Furthermore it is possible to start an application frame in shrunk state.

Frame state

---

Core/clim-basic/decls.lisp
Core/clim-basic/extended-streams/recording.lisp
Core/clim-core/clim-core.asd
Core/clim-core/formatting/bordered-output.lisp
Core/clim-core/incremental-redisplay/propagate.lisp
Core/clim-core/incremental-redisplay/redisplay.lisp
Documentation/Specification/redisplay.tex
Libraries/Drei/drei-redisplay.lisp

This pull request is a small cleanup and a groundwork for the future incremental redisplay change propagation in formatting items like tables and lists.

Propagate changes

---

Apps/Clouseau/README.org

f40063e01 moved the files in Texinfo/ to top level.

Update Closeau readme internal links
